import type { Monster } from './types';

export const MONSTERS: Record<string, Monster> = {
  greenhorn_boar: {
    id: 'greenhorn_boar',
    name: 'Greenhorn Boar',
    zoneIds: ['greenhollow_fields'],
    levelRange: [1, 5],
    level: 3, // placeholder — real tuning against the new formulas happens at Step 10
    combatType: 'melee',
    goldMin: 1,
    goldMax: 3,
    lootTable: [
      { itemId: 'leather_scraps', chance: 0.15, minQty: 1, maxQty: 2 },
      { itemId: 'boar_meat', chance: 0.6, minQty: 1, maxQty: 2 },
      { itemId: 'small_tusk', chance: 0.1, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Charge',
      description: 'Briefly increases movement speed and attack damage.',
      implemented: false,
    },
  },

  forest_wolf: {
    id: 'forest_wolf',
    name: 'Forest Wolf',
    zoneIds: ['greenhollow_fields'],
    levelRange: [3, 8],
    level: 6, // placeholder — real tuning against the new formulas happens at Step 10
    combatType: 'melee',
    goldMin: 2,
    goldMax: 5,
    lootTable: [
      { itemId: 'leather_scraps', chance: 0.2, minQty: 1, maxQty: 2 },
      { itemId: 'wolf_fang', chance: 0.2, minQty: 1, maxQty: 1 },
      { itemId: 'raw_meat', chance: 0.5, minQty: 1, maxQty: 2 },
    ],
    specialAbility: {
      name: 'Pack Howl',
      description: 'Nearby wolves gain increased attack speed.',
      implemented: false,
    },
  },

  wild_kobold: {
    id: 'wild_kobold',
    name: 'Wild Kobold',
    zoneIds: ['greenhollow_fields'],
    levelRange: [5, 10],
    level: 9, // placeholder — real tuning against the new formulas happens at Step 10
    combatType: 'melee',
    goldMin: 3,
    goldMax: 7,
    lootTable: [
      { itemId: 'linen_cloth', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'copper_scrap', chance: 0.25, minQty: 1, maxQty: 1 },
      { itemId: 'small_coin_pouch', chance: 0.1, minQty: 1, maxQty: 1 },
      { itemId: 'rusty_dagger', chance: 0.08, minQty: 1, maxQty: 1 },
      { itemId: 'apprentice_staff', chance: 0.08, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Dirty Strike',
      description: 'Has a chance to briefly reduce player defense.',
      implemented: false,
    },
  },

  thornback_hare: {
    id: 'thornback_hare',
    name: 'Thornback Hare',
    zoneIds: ['greenhollow_fields'],
    levelRange: [2, 6],
    level: 1, // placeholder — real tuning against the new formulas happens at Step 10
    combatType: 'ranged',
    goldMin: 1,
    goldMax: 2,
    lootTable: [
      { itemId: 'leather_scraps', chance: 0.08, minQty: 1, maxQty: 1 },
      { itemId: 'lucky_foot', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'raw_meat', chance: 0.35, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Flee',
      description: 'Occasionally attempts to escape combat.',
      implemented: false,
    },
  },

  // ── Stonecrag Foothills ──────────────────────────────────────────────
  ridge_jackal: {
    id: 'ridge_jackal',
    name: 'Ridge Jackal',
    zoneIds: ['stonecrag_foothills'],
    levelRange: [8, 12],
    level: 10,
    combatType: 'melee',
    goldMin: 4,
    goldMax: 9,
    lootTable: [
      { itemId: 'coarse_hide', chance: 0.55, minQty: 1, maxQty: 2 },
      { itemId: 'raw_meat', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'stone_shard', chance: 0.08, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Snarl',
      description: 'Briefly lowers player accuracy.',
      implemented: false,
    },
  },

  craggy_goat: {
    id: 'craggy_goat',
    name: 'Craggy Goat',
    zoneIds: ['stonecrag_foothills'],
    levelRange: [11, 16],
    level: 13,
    combatType: 'melee',
    goldMin: 5,
    goldMax: 11,
    lootTable: [
      { itemId: 'thick_hide', chance: 0.5, minQty: 1, maxQty: 2 },
      { itemId: 'raw_meat', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'goat_horn', chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Headbutt',
      description: 'A hard-hitting charge attack.',
      implemented: false,
    },
  },

  rubble_crawler: {
    id: 'rubble_crawler',
    name: 'Rubble Crawler',
    zoneIds: ['stonecrag_foothills'],
    levelRange: [14, 19],
    level: 16,
    combatType: 'ranged',
    goldMin: 6,
    goldMax: 13,
    lootTable: [
      { itemId: 'stone_shard', chance: 0.6, minQty: 1, maxQty: 3 },
      { itemId: 'tin_ore', chance: 0.3, minQty: 1, maxQty: 2 },
      { itemId: 'flawed_gem', chance: 0.05, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Rock Slide',
      description: 'Hurls debris for a burst of extra damage.',
      implemented: false,
    },
  },

  highland_bandit: {
    id: 'highland_bandit',
    name: 'Highland Bandit',
    zoneIds: ['stonecrag_foothills'],
    levelRange: [16, 22],
    level: 19,
    combatType: 'ranged',
    goldMin: 9,
    goldMax: 18,
    lootTable: [
      { itemId: 'wool_cloth', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'worn_shiv', chance: 0.2, minQty: 1, maxQty: 1 },
      { itemId: 'bandit_coin_pouch', chance: 0.12, minQty: 1, maxQty: 1 },
      { itemId: 'focusing_wand', chance: 0.07, minQty: 1, maxQty: 1 },
      { itemId: 'stolen_spellband', chance: 0.07, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Backstab',
      description: 'A chance for a large burst of extra damage.',
      implemented: false,
    },
  },

  crag_wolf_alpha: {
    id: 'crag_wolf_alpha',
    name: 'Crag Wolf Alpha',
    zoneIds: ['stonecrag_foothills'],
    levelRange: [19, 25],
    level: 22,
    combatType: 'melee',
    goldMin: 11,
    goldMax: 22,
    lootTable: [
      { itemId: 'sharp_fang', chance: 0.55, minQty: 1, maxQty: 2 },
      { itemId: 'coarse_hide', chance: 0.25, minQty: 1, maxQty: 1 },
      { itemId: 'alpha_pelt', chance: 0.06, minQty: 1, maxQty: 1 },
      { itemId: 'alpha_fang_blade', chance: 0.05, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Pack Leader',
      description: 'Hits harder the longer the fight goes on.',
      implemented: false,
    },
  },

  // ── Emberfall Ridge ──────────────────────────────────────────────────
  cinder_wolf: {
    id: 'cinder_wolf',
    name: 'Cinder Wolf',
    damageSchool: 'fire',
    zoneIds: ['emberfall_ridge'],
    levelRange: [25, 29],
    level: 27,
    combatType: 'melee',
    goldMin: 11,
    goldMax: 20,
    lootTable: [
      { itemId: 'scaled_hide', chance: 0.5, minQty: 1, maxQty: 2 },
      { itemId: 'raw_meat', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'ember_shard', chance: 0.05, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Ember Bite',
      description: 'A searing bite that leaves the wound smoldering.',
      implemented: false,
    },
  },

  ashwing_bat: {
    id: 'ashwing_bat',
    name: 'Ashwing Bat',
    zoneIds: ['emberfall_ridge'],
    levelRange: [27, 32],
    level: 30,
    combatType: 'ranged',
    goldMin: 12,
    goldMax: 22,
    lootTable: [
      { itemId: 'sunpetal', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'stone_shard', chance: 0.2, minQty: 1, maxQty: 1 },
      { itemId: 'obsidian_shard', chance: 0.06, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Sonic Screech',
      description: 'A disorienting shriek that briefly lowers player accuracy.',
      implemented: false,
    },
  },

  molten_crawler: {
    id: 'molten_crawler',
    name: 'Molten Crawler',
    damageSchool: 'fire',
    zoneIds: ['emberfall_ridge'],
    levelRange: [30, 34],
    level: 33,
    combatType: 'magic',
    goldMin: 14,
    goldMax: 26,
    lootTable: [
      { itemId: 'iron_ore', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'stone_shard', chance: 0.3, minQty: 1, maxQty: 2 },
      { itemId: 'obsidian_shard', chance: 0.08, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Magma Spray',
      description: 'Hurls molten rock for a burst of extra damage.',
      implemented: false,
    },
  },

  ridgeback_marauder: {
    id: 'ridgeback_marauder',
    name: 'Ridgeback Marauder',
    zoneIds: ['emberfall_ridge'],
    levelRange: [32, 37],
    level: 35,
    combatType: 'melee',
    goldMin: 18,
    goldMax: 32,
    lootTable: [
      { itemId: 'silk_cloth', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'iron_ore', chance: 0.2, minQty: 1, maxQty: 1 },
      { itemId: 'common_seasoning', chance: 0.25, minQty: 1, maxQty: 2 },
      { itemId: 'serrated_cleaver', chance: 0.06, minQty: 1, maxQty: 1 },
      { itemId: 'embertwined_rod', chance: 0.06, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Brutal Slash',
      description: 'A chance for a large burst of extra damage.',
      implemented: false,
    },
  },

  scorched_drake: {
    id: 'scorched_drake',
    name: 'Scorched Drake',
    damageSchool: 'fire',
    zoneIds: ['emberfall_ridge'],
    levelRange: [36, 40],
    level: 39,
    combatType: 'magic',
    goldMin: 22,
    goldMax: 38,
    lootTable: [
      { itemId: 'scaled_hide', chance: 0.3, minQty: 2, maxQty: 3 },
      { itemId: 'ember_shard', chance: 0.15, minQty: 1, maxQty: 1 },
      { itemId: 'drakes_ember_eye', chance: 0.05, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Flame Breath',
      description: 'A blast of fire that hits harder the longer the fight goes on.',
      implemented: false,
    },
  },

  // ── Dungeon bosses (Phase 8) — real ability rotations via
  // combatEngine/monsterAbilities.ts instead of auto-attack only. ───────
  kobold_chieftain: {
    id: 'kobold_chieftain',
    name: 'Kobold Chieftain',
    zoneIds: ['greenhollow_fields'],
    levelRange: [10, 10],
    level: 10,
    combatType: 'melee',
    goldMin: 8,
    goldMax: 15,
    isBoss: true,
    equippedAbilityIds: ['kobold_chieftain_warcry', 'kobold_chieftain_bash', 'kobold_chieftain_slam'],
    lootTable: [
      { itemId: 'formula_linen_shirt_of_mastery', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_linen_shirt_of_the_gatherer', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_linen_shirt_of_the_artisan', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_linen_shirt_of_learning', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_linen_shirt_of_fortune', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_linen_shirt_of_salvaging', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_linen_shirt_of_preservation', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'linen_cloth', chance: 0.5, minQty: 2, maxQty: 3 },
      { itemId: 'small_coin_pouch', chance: 0.25, minQty: 1, maxQty: 1 },
      { itemId: 'chieftains_warhammer', chance: 0.15, minQty: 1, maxQty: 1 },
      { itemId: 'chieftains_seal', chance: 0.12, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Warlord’s Command',
      description: 'Buffs itself, stuns, and hits far harder than a common kobold.',
      implemented: false,
    },
  },
  alpha_warlord: {
    id: 'alpha_warlord',
    name: 'Alpha Warlord',
    zoneIds: ['stonecrag_foothills'],
    levelRange: [24, 24],
    level: 24,
    combatType: 'melee',
    goldMin: 18,
    goldMax: 30,
    isBoss: true,
    equippedAbilityIds: ['alpha_warlord_howl', 'alpha_warlord_rend', 'alpha_warlord_pounce'],
    lootTable: [
      { itemId: 'formula_wool_shirt_of_mastery', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_wool_shirt_of_the_gatherer', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_wool_shirt_of_the_artisan', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_wool_shirt_of_learning', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_wool_shirt_of_fortune', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_wool_shirt_of_salvaging', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_wool_shirt_of_preservation', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'sharp_fang', chance: 0.5, minQty: 2, maxQty: 3 },
      { itemId: 'alpha_pelt', chance: 0.2, minQty: 1, maxQty: 1 },
      { itemId: 'warlords_signet', chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Warlord of the Depths',
      description: 'A savage pack leader with a real ability rotation — rend, a leaping strike, and a self-buffing howl.',
      implemented: false,
    },
  },
  forgemaster_kaldrun: {
    id: 'forgemaster_kaldrun',
    name: 'Forgemaster Kaldrun',
    damageSchool: 'fire',
    zoneIds: ['emberfall_ridge'],
    levelRange: [40, 40],
    level: 40,
    combatType: 'melee',
    goldMin: 30,
    goldMax: 48,
    isBoss: true,
    equippedAbilityIds: ['kaldrun_warcry', 'kaldrun_hammerfall', 'kaldrun_cinderlash'],
    lootTable: [
      { itemId: 'formula_silk_shirt_of_mastery', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_silk_shirt_of_the_gatherer', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_silk_shirt_of_the_artisan', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_silk_shirt_of_learning', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_silk_shirt_of_fortune', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_silk_shirt_of_salvaging', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_silk_shirt_of_preservation', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'silk_cloth', chance: 0.5, minQty: 2, maxQty: 3 },
      { itemId: 'ember_shard', chance: 0.35, minQty: 1, maxQty: 2 },
      { itemId: 'kaldrun_warhammer', chance: 0.15, minQty: 1, maxQty: 1 },
      { itemId: 'kaldrun_tempered_band', chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Master of the Sundered Forge',
      description: 'A self-styled forgemaster with a real ability rotation — a crushing hammer strike, a smoldering cinder wound, and a self-buffing warcry.',
      implemented: false,
    },
  },

  // ── Cinderfall Depths ────────────────────────────────────────────────
  ash_wraith: {
    id: 'ash_wraith',
    name: 'Ash Wraith',
    damageSchool: 'shadow',
    zoneIds: ['cinderfall_depths'],
    levelRange: [30, 34],
    level: 31,
    combatType: 'magic',
    goldMin: 12,
    goldMax: 22,
    lootTable: [
      { itemId: 'mageweave_cloth', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'smoky_quartz', chance: 0.06, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Chilling Wail',
      description: 'A hollow wail that saps the will to fight.',
      implemented: false,
    },
  },
  cinder_scavenger: {
    id: 'cinder_scavenger',
    name: 'Cinder Scavenger',
    damageSchool: 'fire',
    zoneIds: ['cinderfall_depths'],
    levelRange: [31, 36],
    level: 33,
    combatType: 'ranged',
    goldMin: 14,
    goldMax: 25,
    lootTable: [
      { itemId: 'mithril_ore', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'mageweave_cloth', chance: 0.25, minQty: 1, maxQty: 1 },
      { itemId: 'scavenger_meat', chance: 0.3, minQty: 1, maxQty: 2 },
      { itemId: 'scavenged_hatchet', chance: 0.06, minQty: 1, maxQty: 1 },
      { itemId: 'scavenged_focus', chance: 0.06, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Firebrand Toss',
      description: 'Hurls a smoldering coal for a burst of extra damage.',
      implemented: false,
    },
  },
  ashforge_golem: {
    id: 'ashforge_golem',
    name: 'Ashforge Golem',
    zoneIds: ['cinderfall_depths'],
    levelRange: [34, 38],
    level: 36,
    combatType: 'melee',
    goldMin: 17,
    goldMax: 30,
    lootTable: [
      { itemId: 'mithril_ore', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'smoky_quartz', chance: 0.08, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Ash Slam',
      description: 'A ground-shaking slam that kicks up a blinding cloud of ash.',
      implemented: false,
    },
  },
  ember_stalker: {
    id: 'ember_stalker',
    name: 'Ember Stalker',
    damageSchool: 'fire',
    zoneIds: ['cinderfall_depths'],
    levelRange: [36, 40],
    level: 38,
    combatType: 'magic',
    goldMin: 20,
    goldMax: 35,
    lootTable: [
      { itemId: 'emberpetal', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'ashhide', chance: 0.3, minQty: 1, maxQty: 2 },
      { itemId: 'cindercore_shard', chance: 0.06, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Ember Pounce',
      description: 'A sudden, fire-wreathed lunge.',
      implemented: false,
    },
  },
  ruin_marauder: {
    id: 'ruin_marauder',
    name: 'Ruin Marauder',
    zoneIds: ['cinderfall_depths'],
    levelRange: [38, 44],
    level: 40,
    combatType: 'melee',
    goldMin: 24,
    goldMax: 40,
    lootTable: [
      { itemId: 'ashhide', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'cindercore_shard', chance: 0.08, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Ruinous Strike',
      description: 'A chance for a large burst of extra damage.',
      implemented: false,
    },
  },

  // ── The Molten Scar ──────────────────────────────────────────────────
  cultist_adept: {
    id: 'cultist_adept',
    name: 'Cultist Adept',
    damageSchool: 'fire',
    zoneIds: ['molten_scar'],
    levelRange: [40, 44],
    level: 41,
    combatType: 'magic',
    goldMin: 25,
    goldMax: 42,
    lootTable: [
      { itemId: 'runecloth', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'fire_opal', chance: 0.06, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Firebolt',
      description: 'A bolt of raw flame hurled from a distance.',
      implemented: false,
    },
  },
  living_ember: {
    id: 'living_ember',
    name: 'Living Ember',
    damageSchool: 'fire',
    zoneIds: ['molten_scar'],
    levelRange: [41, 46],
    level: 43,
    combatType: 'magic',
    goldMin: 28,
    goldMax: 46,
    lootTable: [
      { itemId: 'thorium_ore', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'fire_opal', chance: 0.08, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Flare Burst',
      description: 'An unstable burst of elemental fire.',
      implemented: false,
    },
  },
  scaleback_drake: {
    id: 'scaleback_drake',
    name: 'Scaleback Drake',
    zoneIds: ['molten_scar'],
    levelRange: [44, 48],
    level: 46,
    combatType: 'melee',
    goldMin: 32,
    goldMax: 52,
    lootTable: [
      { itemId: 'scaleback_hide', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'cinderbloom', chance: 0.3, minQty: 1, maxQty: 2 },
      { itemId: 'drake_meat', chance: 0.3, minQty: 1, maxQty: 2 },
    ],
    specialAbility: {
      name: 'Tail Sweep',
      description: 'A wide sweeping strike.',
      implemented: false,
    },
  },
  cultist_zealot: {
    id: 'cultist_zealot',
    name: 'Cultist Zealot',
    zoneIds: ['molten_scar'],
    levelRange: [46, 50],
    level: 48,
    combatType: 'melee',
    goldMin: 36,
    goldMax: 58,
    lootTable: [
      { itemId: 'runecloth', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'zealots_blade', chance: 0.06, minQty: 1, maxQty: 1 },
      { itemId: 'zealots_icon', chance: 0.06, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Zealous Fervor',
      description: 'A frenzied flurry of blows.',
      implemented: false,
    },
  },
  magma_hound: {
    id: 'magma_hound',
    name: 'Magma Hound',
    damageSchool: 'fire',
    zoneIds: ['molten_scar'],
    levelRange: [48, 54],
    level: 50,
    combatType: 'magic',
    goldMin: 40,
    goldMax: 64,
    lootTable: [
      { itemId: 'scaleback_hide', chance: 0.35, minQty: 1, maxQty: 2 },
      { itemId: 'hound_meat', chance: 0.35, minQty: 1, maxQty: 2 },
      { itemId: 'magma_heart', chance: 0.08, minQty: 1, maxQty: 1 },
      { itemId: 'magma_forged_band', chance: 0.08, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Magma Breath',
      description: 'A gout of molten fire.',
      implemented: false,
    },
  },

  // ── Cinderheart Crater ───────────────────────────────────────────────
  emberlord_cultist: {
    id: 'emberlord_cultist',
    name: 'Emberlord Cultist',
    damageSchool: 'fire',
    zoneIds: ['cinderheart_crater'],
    levelRange: [48, 52],
    level: 49,
    combatType: 'magic',
    goldMin: 42,
    goldMax: 66,
    voidShardsMin: 1,
    voidShardsMax: 2,
    lootTable: [
      { itemId: 'ember_cloth', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'heartflame_crystal', chance: 0.06, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Devotion of Flame',
      description: 'Channels the crater’s heat into a searing bolt.',
      implemented: false,
    },
  },
  flamewalker: {
    id: 'flamewalker',
    name: 'Flamewalker',
    damageSchool: 'fire',
    zoneIds: ['cinderheart_crater'],
    levelRange: [50, 54],
    level: 52,
    combatType: 'magic',
    goldMin: 46,
    goldMax: 72,
    voidShardsMin: 1,
    voidShardsMax: 2,
    lootTable: [
      { itemId: 'obsidian_ore', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'heartflame_crystal', chance: 0.08, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Wildfire',
      description: 'A spreading blaze that grows fiercer over time.',
      implemented: false,
    },
  },
  charhide_behemoth: {
    id: 'charhide_behemoth',
    name: 'Charhide Behemoth',
    zoneIds: ['cinderheart_crater'],
    levelRange: [52, 56],
    level: 54,
    combatType: 'melee',
    goldMin: 50,
    goldMax: 78,
    voidShardsMin: 1,
    voidShardsMax: 2,
    lootTable: [
      { itemId: 'emberscale_hide', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'emberheart_bloom', chance: 0.3, minQty: 1, maxQty: 2 },
      { itemId: 'behemoth_flank', chance: 0.3, minQty: 1, maxQty: 2 },
    ],
    specialAbility: {
      name: 'Crushing Charge',
      description: 'A devastating charge from a creature built like a landslide.',
      implemented: false,
    },
  },
  ashfall_harbinger: {
    id: 'ashfall_harbinger',
    name: 'Ashfall Harbinger',
    damageSchool: 'fire',
    zoneIds: ['cinderheart_crater'],
    levelRange: [54, 58],
    level: 56,
    combatType: 'ranged',
    goldMin: 54,
    goldMax: 84,
    voidShardsMin: 1,
    voidShardsMax: 2,
    lootTable: [
      { itemId: 'ember_cloth', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'rare_seasoning', chance: 0.2, minQty: 1, maxQty: 2 },
      { itemId: 'harbingers_talon', chance: 0.06, minQty: 1, maxQty: 1 },
      { itemId: 'harbingers_omen', chance: 0.06, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Cinder Rain',
      description: 'Rains burning cinders down from above.',
      implemented: false,
    },
  },
  emberguard_sentinel: {
    id: 'emberguard_sentinel',
    name: 'Emberguard Sentinel',
    zoneIds: ['cinderheart_crater'],
    levelRange: [56, 60],
    level: 58,
    combatType: 'melee',
    goldMin: 58,
    goldMax: 90,
    voidShardsMin: 1,
    voidShardsMax: 2,
    lootTable: [
      { itemId: 'obsidian_ore', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'sentinels_signet', chance: 0.06, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Guardian’s Wrath',
      description: 'A punishing strike from an ancient guardian construct.',
      implemented: false,
    },
  },

  // ── Dungeon bosses ───────────────────────────────────────────────────
  ashen_overseer: {
    id: 'ashen_overseer',
    name: 'Ashen Overseer',
    damageSchool: 'fire',
    zoneIds: ['cinderfall_depths'],
    levelRange: [44, 44],
    level: 44,
    combatType: 'melee',
    goldMin: 34,
    goldMax: 54,
    isBoss: true,
    equippedAbilityIds: ['ashen_overseer_warcry', 'ashen_overseer_slam', 'ashen_overseer_cinderwound'],
    lootTable: [
      { itemId: 'formula_mageweave_shirt_of_mastery', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_mageweave_shirt_of_the_gatherer', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_mageweave_shirt_of_the_artisan', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_mageweave_shirt_of_learning', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_mageweave_shirt_of_fortune', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_mageweave_shirt_of_salvaging', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_mageweave_shirt_of_preservation', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'mageweave_cloth', chance: 0.5, minQty: 2, maxQty: 3 },
      { itemId: 'cindercore_shard', chance: 0.35, minQty: 1, maxQty: 2 },
      { itemId: 'overseers_greatmace_damaged', chance: 0.15, minQty: 1, maxQty: 1 },
      { itemId: 'overseers_band', chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'The Last Overseer',
      description: 'A corrupted dwarven construct with a real ability rotation — a crushing slam, a smoldering wound, and a self-buffing warcry.',
      implemented: false,
    },
  },
  molten_herald: {
    id: 'molten_herald',
    name: 'Molten Herald',
    damageSchool: 'fire',
    zoneIds: ['molten_scar'],
    levelRange: [54, 54],
    level: 54,
    combatType: 'magic',
    goldMin: 50,
    goldMax: 78,
    isBoss: true,
    equippedAbilityIds: ['molten_herald_summon', 'molten_herald_eruption', 'molten_herald_scorch'],
    lootTable: [
      { itemId: 'formula_runecloth_shirt_of_mastery', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_runecloth_shirt_of_the_gatherer', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_runecloth_shirt_of_the_artisan', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_runecloth_shirt_of_learning', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_runecloth_shirt_of_fortune', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_runecloth_shirt_of_salvaging', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_runecloth_shirt_of_preservation', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'runecloth', chance: 0.5, minQty: 2, maxQty: 3 },
      { itemId: 'magma_heart', chance: 0.35, minQty: 1, maxQty: 2 },
      { itemId: 'heralds_ember_band', chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Herald of the Rift',
      description: 'A fire elemental lieutenant with a real ability rotation — a self-buffing invocation, a burst eruption, and a scorching wound.',
      implemented: false,
    },
  },
  pyraxis: {
    id: 'pyraxis',
    name: 'Pyraxis, Warden of the Cinderheart',
    damageSchool: 'fire',
    zoneIds: ['cinderheart_crater'],
    levelRange: [60, 60],
    level: 60,
    combatType: 'melee',
    goldMin: 70,
    goldMax: 105,
    // The dungeon's final boss — a much bigger Void Shard reward than the
    // open-world Cinderheart Crater monsters above, consistent with a
    // repeatable dungeon-boss kill being worth more than a trash mob.
    voidShardsMin: 5,
    voidShardsMax: 8,
    isBoss: true,
    equippedAbilityIds: ['pyraxis_warcry', 'pyraxis_slam', 'pyraxis_cinderwound'],
    lootTable: [
      { itemId: 'formula_ember_shirt_of_mastery', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_ember_shirt_of_the_gatherer', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_ember_shirt_of_the_artisan', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_ember_shirt_of_learning', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_ember_shirt_of_fortune', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_ember_shirt_of_salvaging', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'formula_ember_shirt_of_preservation', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'ember_cloth', chance: 0.5, minQty: 2, maxQty: 3 },
      { itemId: 'emberlords_ash', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'pyraxis_flank', chance: 0.3, minQty: 1, maxQty: 2 },
      { itemId: 'pyraxis_warblade_damaged', chance: 0.15, minQty: 1, maxQty: 1 },
      // Rare recipe drop — matches the design brief's "obtaining the
      // recipe is only one part of the process" example almost exactly
      // (a boss-dropped formula for a dish that still needs its own
      // boss-dropped meat plus other ingredients gathered separately).
      { itemId: 'recipe_pyraxis_flame_seared_flank', chance: 0.08, minQty: 1, maxQty: 1 },
    ],
    specialAbility: {
      name: 'Warden of the Cinderheart',
      description: 'The guardian of the crater’s heart, with a real ability rotation — a self-buffing warcry, a crushing slam, and a smoldering wound.',
      implemented: false,
    },
  },
};
