import type { Monster } from './types';

export const MONSTERS: Record<string, Monster> = {
  greenhorn_boar: {
    id: 'greenhorn_boar',
    name: 'Greenhorn Boar',
    zoneIds: ['greenhollow_fields'],
    levelRange: [1, 5],
    level: 3, // placeholder — real tuning against the new formulas happens at Step 10
    hp: 28,
    attackPower: 3,
    defense: 1,
    attackIntervalSeconds: 2.5,
    xpReward: 8,
    goldMin: 1,
    goldMax: 3,
    lootTable: [
      { itemId: 'light_leather', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'boar_meat', chance: 0.6, minQty: 1, maxQty: 2 },
      { itemId: 'small_tusk', chance: 0.1, minQty: 1, maxQty: 1 },
    ],
    skinnable: true,
    skinningYield: {
      requiredSkinningLevel: 1,
      itemId: 'light_leather',
      chance: 0.9,
      minQty: 1,
      maxQty: 2,
      actionSeconds: 6,
    },
    specialAbility: {
      name: 'Charge',
      description: 'Briefly increases movement speed and attack damage.',
      implemented: false,
    },
  },

  forest_wolf: {
    id: 'forest_wolf',
    name: 'Forest Wolf',
    zoneIds: ['greenhollow_fields'],
    levelRange: [3, 8],
    level: 6, // placeholder — real tuning against the new formulas happens at Step 10
    hp: 32,
    attackPower: 5,
    defense: 2,
    attackIntervalSeconds: 2.0,
    xpReward: 14,
    goldMin: 2,
    goldMax: 5,
    lootTable: [
      { itemId: 'light_leather', chance: 0.55, minQty: 1, maxQty: 2 },
      { itemId: 'wolf_fang', chance: 0.2, minQty: 1, maxQty: 1 },
      { itemId: 'raw_meat', chance: 0.5, minQty: 1, maxQty: 2 },
    ],
    skinnable: true,
    skinningYield: {
      requiredSkinningLevel: 1,
      itemId: 'light_leather',
      chance: 0.9,
      minQty: 1,
      maxQty: 2,
      actionSeconds: 6,
    },
    specialAbility: {
      name: 'Pack Howl',
      description: 'Nearby wolves gain increased attack speed.',
      implemented: false,
    },
  },

  wild_kobold: {
    id: 'wild_kobold',
    name: 'Wild Kobold',
    zoneIds: ['greenhollow_fields'],
    levelRange: [5, 10],
    level: 9, // placeholder — real tuning against the new formulas happens at Step 10
    hp: 40,
    attackPower: 6,
    defense: 3,
    attackIntervalSeconds: 2.2,
    xpReward: 20,
    goldMin: 3,
    goldMax: 7,
    lootTable: [
      { itemId: 'linen_cloth', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'copper_scrap', chance: 0.25, minQty: 1, maxQty: 1 },
      { itemId: 'small_coin_pouch', chance: 0.1, minQty: 1, maxQty: 1 },
      { itemId: 'rusty_dagger', chance: 0.08, minQty: 1, maxQty: 1 },
    ],
    skinnable: false,
    specialAbility: {
      name: 'Dirty Strike',
      description: 'Has a chance to briefly reduce player defense.',
      implemented: false,
    },
  },

  thornback_hare: {
    id: 'thornback_hare',
    name: 'Thornback Hare',
    zoneIds: ['greenhollow_fields'],
    levelRange: [2, 6],
    level: 1, // placeholder — real tuning against the new formulas happens at Step 10
    hp: 20,
    attackPower: 2,
    defense: 1,
    attackIntervalSeconds: 1.8,
    xpReward: 6,
    goldMin: 1,
    goldMax: 2,
    lootTable: [
      { itemId: 'light_leather', chance: 0.2, minQty: 1, maxQty: 1 },
      { itemId: 'lucky_foot', chance: 0.05, minQty: 1, maxQty: 1 },
      { itemId: 'raw_meat', chance: 0.35, minQty: 1, maxQty: 1 },
    ],
    skinnable: true,
    skinningYield: {
      requiredSkinningLevel: 1,
      itemId: 'light_leather',
      chance: 0.7,
      minQty: 1,
      maxQty: 1,
      actionSeconds: 6,
    },
    specialAbility: {
      name: 'Flee',
      description: 'Occasionally attempts to escape combat.',
      implemented: false,
    },
  },

  // ── Stonecrag Foothills ──────────────────────────────────────────────
  ridge_jackal: {
    id: 'ridge_jackal',
    name: 'Ridge Jackal',
    zoneIds: ['stonecrag_foothills'],
    levelRange: [8, 12],
    level: 10,
    hp: 42,
    attackPower: 7,
    defense: 3,
    attackIntervalSeconds: 2.0,
    xpReward: 500,
    goldMin: 4,
    goldMax: 9,
    lootTable: [
      { itemId: 'coarse_hide', chance: 0.55, minQty: 1, maxQty: 2 },
      { itemId: 'raw_meat', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'stone_shard', chance: 0.08, minQty: 1, maxQty: 1 },
    ],
    skinnable: true,
    skinningYield: {
      requiredSkinningLevel: 8,
      itemId: 'coarse_hide',
      chance: 0.85,
      minQty: 1,
      maxQty: 2,
      actionSeconds: 6,
    },
    specialAbility: {
      name: 'Snarl',
      description: 'Briefly lowers player accuracy.',
      implemented: false,
    },
  },

  craggy_goat: {
    id: 'craggy_goat',
    name: 'Craggy Goat',
    zoneIds: ['stonecrag_foothills'],
    levelRange: [11, 16],
    level: 13,
    hp: 48,
    attackPower: 9,
    defense: 4,
    attackIntervalSeconds: 2.2,
    xpReward: 650,
    goldMin: 5,
    goldMax: 11,
    lootTable: [
      { itemId: 'thick_hide', chance: 0.5, minQty: 1, maxQty: 2 },
      { itemId: 'raw_meat', chance: 0.4, minQty: 1, maxQty: 2 },
      { itemId: 'goat_horn', chance: 0.15, minQty: 1, maxQty: 1 },
    ],
    skinnable: true,
    skinningYield: {
      requiredSkinningLevel: 12,
      itemId: 'thick_hide',
      chance: 0.85,
      minQty: 1,
      maxQty: 2,
      actionSeconds: 7,
    },
    specialAbility: {
      name: 'Headbutt',
      description: 'A hard-hitting charge attack.',
      implemented: false,
    },
  },

  rubble_crawler: {
    id: 'rubble_crawler',
    name: 'Rubble Crawler',
    zoneIds: ['stonecrag_foothills'],
    levelRange: [14, 19],
    level: 16,
    hp: 55,
    attackPower: 11,
    defense: 6,
    attackIntervalSeconds: 2.4,
    xpReward: 800,
    goldMin: 6,
    goldMax: 13,
    lootTable: [
      { itemId: 'stone_shard', chance: 0.6, minQty: 1, maxQty: 3 },
      { itemId: 'tin_ore', chance: 0.3, minQty: 1, maxQty: 2 },
      { itemId: 'flawed_gem', chance: 0.05, minQty: 1, maxQty: 1 },
    ],
    skinnable: false,
    specialAbility: {
      name: 'Rock Slide',
      description: 'Hurls debris for a burst of extra damage.',
      implemented: false,
    },
  },

  highland_bandit: {
    id: 'highland_bandit',
    name: 'Highland Bandit',
    zoneIds: ['stonecrag_foothills'],
    levelRange: [16, 22],
    level: 19,
    hp: 62,
    attackPower: 13,
    defense: 7,
    attackIntervalSeconds: 2.0,
    xpReward: 950,
    goldMin: 9,
    goldMax: 18,
    lootTable: [
      { itemId: 'coarse_cloth', chance: 0.45, minQty: 1, maxQty: 2 },
      { itemId: 'worn_shiv', chance: 0.2, minQty: 1, maxQty: 1 },
      { itemId: 'bandit_coin_pouch', chance: 0.12, minQty: 1, maxQty: 1 },
    ],
    skinnable: false,
    specialAbility: {
      name: 'Backstab',
      description: 'A chance for a large burst of extra damage.',
      implemented: false,
    },
  },

  crag_wolf_alpha: {
    id: 'crag_wolf_alpha',
    name: 'Crag Wolf Alpha',
    zoneIds: ['stonecrag_foothills'],
    levelRange: [19, 25],
    level: 22,
    hp: 70,
    attackPower: 16,
    defense: 8,
    attackIntervalSeconds: 1.8,
    xpReward: 1100,
    goldMin: 11,
    goldMax: 22,
    lootTable: [
      { itemId: 'sharp_fang', chance: 0.55, minQty: 1, maxQty: 2 },
      { itemId: 'coarse_hide', chance: 0.25, minQty: 1, maxQty: 1 },
    ],
    skinnable: true,
    skinningYield: {
      requiredSkinningLevel: 18,
      itemId: 'alpha_pelt',
      chance: 0.3,
      minQty: 1,
      maxQty: 1,
      actionSeconds: 10,
    },
    specialAbility: {
      name: 'Pack Leader',
      description: 'Hits harder the longer the fight goes on.',
      implemented: false,
    },
  },
};
