import type { Recipe } from './types';

export const RECIPES: Record<string, Recipe> = {
  light_leather: {
    id: 'light_leather',
    name: 'Light Leather',
    profession: 'leatherworking',
    requiredSkill: 1,
    resultItemId: 'light_leather',
    resultQuantity: 1,
    materials: [{ itemId: 'leather_scraps', quantity: 5 }],
    craftSeconds: 5,
    xpAward: 1,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  leather_boots: {
    id: 'leather_boots',
    name: 'Leather Boots',
    profession: 'leatherworking',
    requiredSkill: 1,
    resultItemId: 'leather_boots',
    resultQuantity: 1,
    materials: [
      { itemId: 'light_leather', quantity: 4 },
      { itemId: 'rabbit_pelt', quantity: 2 },
    ],
    craftSeconds: 5,
    xpAward: 1,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  leather_gloves: {
    id: 'leather_gloves',
    name: 'Leather Gloves',
    profession: 'leatherworking',
    requiredSkill: 8,
    resultItemId: 'leather_gloves',
    resultQuantity: 1,
    materials: [
      { itemId: 'light_leather', quantity: 5 },
      { itemId: 'linen_cloth', quantity: 2 },
    ],
    craftSeconds: 6.1,
    xpAward: 7,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  leather_cap: {
    id: 'leather_cap',
    name: 'Leather Cap',
    profession: 'leatherworking',
    requiredSkill: 17,
    resultItemId: 'leather_cap',
    resultQuantity: 1,
    materials: [
      { itemId: 'light_leather', quantity: 6 },
      { itemId: 'linen_cloth', quantity: 3 },
      { itemId: 'jackal_fur', quantity: 2 },
    ],
    craftSeconds: 7.4,
    xpAward: 16,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  copper_bar: {
    id: 'copper_bar',
    name: 'Copper Bar',
    profession: 'mining',
    requiredSkill: 1,
    resultItemId: 'copper_bar',
    resultQuantity: 1,
    materials: [{ itemId: 'copper_ore', quantity: 1 }],
    craftSeconds: 4,
    xpAward: 5,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  tin_bar: {
    id: 'tin_bar',
    name: 'Tin Bar',
    profession: 'mining',
    requiredSkill: 10,
    resultItemId: 'tin_bar',
    resultQuantity: 1,
    materials: [{ itemId: 'tin_ore', quantity: 1 }],
    craftSeconds: 5,
    xpAward: 8,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  silver_bar: {
    id: 'silver_bar',
    name: 'Silver Bar',
    profession: 'mining',
    requiredSkill: 10,
    resultItemId: 'silver_bar',
    resultQuantity: 1,
    materials: [{ itemId: 'silver_ore', quantity: 1 }],
    craftSeconds: 5,
    xpAward: 9,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  bronze_bar: {
    id: 'bronze_bar',
    name: 'Bronze Bar',
    profession: 'mining',
    requiredSkill: 10,
    resultItemId: 'bronze_bar',
    resultQuantity: 1,
    materials: [
      { itemId: 'copper_bar', quantity: 1 },
      { itemId: 'tin_bar', quantity: 1 },
    ],
    craftSeconds: 6,
    xpAward: 12,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  linen_robe: {
    id: 'linen_robe',
    name: 'Linen Robe',
    profession: 'tailoring',
    requiredSkill: 1,
    resultItemId: 'linen_robe',
    resultQuantity: 1,
    materials: [
      { itemId: 'linen_cloth', quantity: 5 },
      { itemId: 'simple_thread', quantity: 2 },
    ],
    craftSeconds: 8,
    xpAward: 1,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  linen_gloves: {
    id: 'linen_gloves',
    name: 'Linen Gloves',
    profession: 'tailoring',
    requiredSkill: 3,
    resultItemId: 'linen_gloves',
    resultQuantity: 1,
    materials: [
      { itemId: 'linen_cloth', quantity: 4 },
      { itemId: 'simple_thread', quantity: 1 },
    ],
    craftSeconds: 8.4,
    xpAward: 4,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  linen_cap: {
    id: 'linen_cap',
    name: 'Linen Cap',
    profession: 'tailoring',
    requiredSkill: 4,
    resultItemId: 'linen_cap',
    resultQuantity: 1,
    materials: [
      { itemId: 'linen_cloth', quantity: 5 },
      { itemId: 'simple_thread', quantity: 2 },
    ],
    craftSeconds: 8.5,
    xpAward: 5,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  linen_boots: {
    id: 'linen_boots',
    name: 'Linen Boots',
    profession: 'tailoring',
    requiredSkill: 4,
    resultItemId: 'linen_boots',
    resultQuantity: 1,
    materials: [
      { itemId: 'linen_cloth', quantity: 4 },
      { itemId: 'simple_thread', quantity: 1 },
    ],
    craftSeconds: 8.5,
    xpAward: 5,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  sage_leggings: {
    id: 'sage_leggings',
    name: 'Sage-Woven Leggings',
    profession: 'tailoring',
    requiredSkill: 6,
    resultItemId: 'sage_leggings',
    resultQuantity: 1,
    materials: [
      { itemId: 'coarse_cloth', quantity: 5 },
      { itemId: 'mountain_sage', quantity: 3 },
    ],
    craftSeconds: 8.9,
    xpAward: 8,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Stonecrag Foothills leatherworking ───────────────────────────────
  coarse_leather: {
    id: 'coarse_leather',
    name: 'Coarse Leather',
    profession: 'leatherworking',
    requiredSkill: 21,
    resultItemId: 'coarse_leather',
    resultQuantity: 1,
    materials: [{ itemId: 'coarse_hide', quantity: 5 }],
    craftSeconds: 8,
    xpAward: 20,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  reinforced_leather_vest: {
    id: 'reinforced_leather_vest',
    name: 'Reinforced Leather Vest',
    profession: 'leatherworking',
    requiredSkill: 26,
    resultItemId: 'reinforced_leather_vest',
    resultQuantity: 1,
    materials: [
      { itemId: 'coarse_leather', quantity: 5 },
      { itemId: 'thick_hide', quantity: 2 },
    ],
    craftSeconds: 8.8,
    xpAward: 25,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  alphahide_gloves: {
    id: 'alphahide_gloves',
    name: 'Alphahide Gloves',
    profession: 'leatherworking',
    requiredSkill: 35,
    resultItemId: 'alphahide_gloves',
    resultQuantity: 1,
    materials: [
      { itemId: 'coarse_leather', quantity: 3 },
      { itemId: 'alpha_pelt', quantity: 1 },
    ],
    craftSeconds: 10.2,
    xpAward: 36,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  thick_hide_cap: {
    id: 'thick_hide_cap',
    name: 'Thick Hide Cap',
    profession: 'leatherworking',
    requiredSkill: 32,
    resultItemId: 'thick_hide_cap',
    resultQuantity: 1,
    materials: [{ itemId: 'coarse_leather', quantity: 4 }],
    craftSeconds: 9.7,
    xpAward: 32,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ridgehide_boots: {
    id: 'ridgehide_boots',
    name: 'Ridgehide Boots',
    profession: 'leatherworking',
    requiredSkill: 39,
    resultItemId: 'ridgehide_boots',
    resultQuantity: 1,
    materials: [
      { itemId: 'coarse_leather', quantity: 3 },
      { itemId: 'thick_hide', quantity: 1 },
    ],
    craftSeconds: 10.8,
    xpAward: 41,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Alchemy ───────────────────────────────────────────────────────────
  minor_healing_draught: {
    id: 'minor_healing_draught',
    name: 'Minor Healing Draught',
    profession: 'alchemy',
    requiredSkill: 1,
    resultItemId: 'minor_healing_draught',
    resultQuantity: 1,
    materials: [
      { itemId: 'peacebloom', quantity: 3 },
      { itemId: 'wildroot', quantity: 1 },
    ],
    craftSeconds: 6,
    xpAward: 2,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  minor_mana_draught: {
    id: 'minor_mana_draught',
    name: 'Minor Mana Draught',
    profession: 'alchemy',
    requiredSkill: 3,
    resultItemId: 'minor_mana_draught',
    resultQuantity: 1,
    materials: [{ itemId: 'peacebloom', quantity: 4 }],
    craftSeconds: 6.3,
    xpAward: 6,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  sage_healing_potion: {
    id: 'sage_healing_potion',
    name: 'Sage Healing Potion',
    profession: 'alchemy',
    requiredSkill: 5,
    resultItemId: 'sage_healing_potion',
    resultQuantity: 1,
    materials: [
      { itemId: 'mountain_sage', quantity: 3 },
      { itemId: 'frostcap', quantity: 1 },
    ],
    craftSeconds: 6.5,
    xpAward: 9,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  sunpetal_elixir: {
    id: 'sunpetal_elixir',
    name: 'Sunpetal Elixir',
    profession: 'alchemy',
    requiredSkill: 10,
    resultItemId: 'sunpetal_elixir',
    resultQuantity: 1,
    materials: [
      { itemId: 'sunpetal', quantity: 4 },
      { itemId: 'emberleaf', quantity: 2 },
    ],
    craftSeconds: 7.2,
    xpAward: 16,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Emberfall Ridge smithing ──────────────────────────────────────────
  iron_bar: {
    id: 'iron_bar',
    name: 'Iron Bar',
    profession: 'mining',
    requiredSkill: 25,
    resultItemId: 'iron_bar',
    resultQuantity: 1,
    materials: [{ itemId: 'iron_ore', quantity: 1 }],
    craftSeconds: 8,
    xpAward: 16,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  steel_bar: {
    id: 'steel_bar',
    name: 'Steel Bar',
    profession: 'mining',
    requiredSkill: 28,
    resultItemId: 'steel_bar',
    resultQuantity: 1,
    materials: [{ itemId: 'iron_ore', quantity: 2 }],
    craftSeconds: 9,
    xpAward: 20,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  // ── Emberfall Ridge leatherworking ────────────────────────────────────
  scaled_leather: {
    id: 'scaled_leather',
    name: 'Scaled Leather',
    profession: 'leatherworking',
    requiredSkill: 44,
    resultItemId: 'scaled_leather',
    resultQuantity: 1,
    materials: [{ itemId: 'scaled_hide', quantity: 5 }],
    craftSeconds: 11.5,
    xpAward: 47,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaled_leggings: {
    id: 'scaled_leggings',
    name: 'Scaled Leggings',
    profession: 'leatherworking',
    requiredSkill: 50,
    resultItemId: 'scaled_leggings',
    resultQuantity: 1,
    materials: [{ itemId: 'scaled_leather', quantity: 5 }],
    craftSeconds: 12.4,
    xpAward: 54,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  drakescale_boots: {
    id: 'drakescale_boots',
    name: 'Drakescale Boots',
    profession: 'leatherworking',
    requiredSkill: 59,
    resultItemId: 'drakescale_boots',
    resultQuantity: 1,
    materials: [
      { itemId: 'scaled_leather', quantity: 4 },
      { itemId: 'ember_shard', quantity: 1 },
    ],
    craftSeconds: 13.8,
    xpAward: 65,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaled_gloves: {
    id: 'scaled_gloves', name: 'Scaled Gloves', profession: 'leatherworking', requiredSkill: 46,
    resultItemId: 'scaled_gloves', resultQuantity: 1,
    materials: [
      { itemId: 'scaled_leather', quantity: 3 },
      { itemId: 'cinderwolf_pelt', quantity: 2 },
    ],
    craftSeconds: 11.8, xpAward: 49,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaled_cap: {
    id: 'scaled_cap', name: 'Scaled Cap', profession: 'leatherworking', requiredSkill: 53,
    resultItemId: 'scaled_cap', resultQuantity: 1,
    materials: [{ itemId: 'scaled_leather', quantity: 4 }],
    craftSeconds: 12.9, xpAward: 58,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Emberfall Ridge tailoring ─────────────────────────────────────────
  heavy_robe: {
    id: 'heavy_robe',
    name: 'Heavy Robe',
    profession: 'tailoring',
    requiredSkill: 13,
    resultItemId: 'heavy_robe',
    resultQuantity: 1,
    materials: [
      { itemId: 'heavy_cloth', quantity: 5 },
      { itemId: 'simple_thread', quantity: 2 },
    ],
    craftSeconds: 10.2,
    xpAward: 20,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  heavy_leggings: {
    id: 'heavy_leggings', name: 'Heavy Leggings', profession: 'tailoring', requiredSkill: 15,
    resultItemId: 'heavy_leggings', resultQuantity: 1,
    materials: [{ itemId: 'heavy_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 10.5, xpAward: 24,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  heavy_gloves: {
    id: 'heavy_gloves', name: 'Heavy Gloves', profession: 'tailoring', requiredSkill: 14,
    resultItemId: 'heavy_gloves', resultQuantity: 1,
    materials: [{ itemId: 'heavy_cloth', quantity: 3 }],
    craftSeconds: 10.4, xpAward: 22,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  heavy_cap: {
    id: 'heavy_cap', name: 'Heavy Cap', profession: 'tailoring', requiredSkill: 16,
    resultItemId: 'heavy_cap', resultQuantity: 1,
    materials: [{ itemId: 'heavy_cloth', quantity: 4 }],
    craftSeconds: 10.7, xpAward: 26,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  heavy_boots: {
    id: 'heavy_boots', name: 'Heavy Boots', profession: 'tailoring', requiredSkill: 14,
    resultItemId: 'heavy_boots', resultQuantity: 1,
    materials: [{ itemId: 'heavy_cloth', quantity: 4 }],
    craftSeconds: 10.4, xpAward: 22,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Cinderfall Depths ──────────────────────────────────────────────────
  mithril_bar: {
    id: 'mithril_bar', name: 'Mithril Bar', profession: 'mining', requiredSkill: 30,
    resultItemId: 'mithril_bar', resultQuantity: 1,
    materials: [{ itemId: 'mithril_ore', quantity: 1 }],
    craftSeconds: 11, xpAward: 24,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  gold_bar: {
    id: 'gold_bar', name: 'Gold Bar', profession: 'mining', requiredSkill: 30,
    resultItemId: 'gold_bar', resultQuantity: 1,
    materials: [{ itemId: 'gold_ore', quantity: 1 }],
    craftSeconds: 11, xpAward: 25,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashhide_leather: {
    id: 'ashhide_leather', name: 'Ashhide Leather', profession: 'leatherworking', requiredSkill: 53,
    resultItemId: 'ashhide_leather', resultQuantity: 1,
    materials: [
      { itemId: 'ashhide', quantity: 5 },
      { itemId: 'scavenger_hide', quantity: 2 },
    ],
    craftSeconds: 12.9, xpAward: 58,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashhide_leggings: {
    id: 'ashhide_leggings', name: 'Ashhide Leggings', profession: 'leatherworking', requiredSkill: 59,
    resultItemId: 'ashhide_leggings', resultQuantity: 1,
    materials: [{ itemId: 'ashhide_leather', quantity: 5 }],
    craftSeconds: 13.8, xpAward: 65,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashhide_boots: {
    id: 'ashhide_boots', name: 'Ashhide Boots', profession: 'leatherworking', requiredSkill: 68,
    resultItemId: 'ashhide_boots', resultQuantity: 1,
    materials: [{ itemId: 'ashhide_leather', quantity: 4 }, { itemId: 'cindercore_shard', quantity: 1 }],
    craftSeconds: 15.2, xpAward: 77,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashhide_gloves: {
    id: 'ashhide_gloves', name: 'Ashhide Gloves', profession: 'leatherworking', requiredSkill: 55,
    resultItemId: 'ashhide_gloves', resultQuantity: 1,
    materials: [{ itemId: 'ashhide_leather', quantity: 3 }],
    craftSeconds: 13.2, xpAward: 60,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashhide_cap: {
    id: 'ashhide_cap', name: 'Ashhide Cap', profession: 'leatherworking', requiredSkill: 62,
    resultItemId: 'ashhide_cap', resultQuantity: 1,
    materials: [{ itemId: 'ashhide_leather', quantity: 4 }],
    craftSeconds: 14.2, xpAward: 69,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashwoven_robe: {
    id: 'ashwoven_robe', name: 'Ashwoven Robe', profession: 'tailoring', requiredSkill: 16,
    resultItemId: 'ashwoven_robe', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 10.7, xpAward: 26,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashwoven_leggings: {
    id: 'ashwoven_leggings', name: 'Ashwoven Leggings', profession: 'tailoring', requiredSkill: 16,
    resultItemId: 'ashwoven_leggings', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 10.7, xpAward: 26,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashwoven_gloves: {
    id: 'ashwoven_gloves', name: 'Ashwoven Gloves', profession: 'tailoring', requiredSkill: 15,
    resultItemId: 'ashwoven_gloves', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 3 }],
    craftSeconds: 10.5, xpAward: 24,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashwoven_cap: {
    id: 'ashwoven_cap', name: 'Ashwoven Cap', profession: 'tailoring', requiredSkill: 17,
    resultItemId: 'ashwoven_cap', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 4 }],
    craftSeconds: 10.9, xpAward: 28,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashwoven_boots: {
    id: 'ashwoven_boots', name: 'Ashwoven Boots', profession: 'tailoring', requiredSkill: 17,
    resultItemId: 'ashwoven_boots', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 4 }],
    craftSeconds: 10.9, xpAward: 28,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberpetal_tonic: {
    id: 'emberpetal_tonic', name: 'Emberpetal Tonic', profession: 'alchemy', requiredSkill: 12,
    resultItemId: 'emberpetal_tonic', resultQuantity: 1,
    materials: [
      { itemId: 'emberpetal', quantity: 4 },
      { itemId: 'ashroot', quantity: 2 },
    ],
    craftSeconds: 7.4, xpAward: 19,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── The Molten Scar ────────────────────────────────────────────────────
  thorium_bar: {
    id: 'thorium_bar', name: 'Thorium Bar', profession: 'mining', requiredSkill: 40,
    resultItemId: 'thorium_bar', resultQuantity: 1,
    materials: [{ itemId: 'thorium_ore', quantity: 1 }],
    craftSeconds: 13, xpAward: 30,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaleback_leather: {
    id: 'scaleback_leather', name: 'Scaleback Leather', profession: 'leatherworking', requiredSkill: 71,
    resultItemId: 'scaleback_leather', resultQuantity: 1,
    materials: [
      { itemId: 'scaleback_hide', quantity: 5 },
      { itemId: 'scaleback_scale', quantity: 2 },
    ],
    craftSeconds: 15.6, xpAward: 81,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaleback_leggings: {
    id: 'scaleback_leggings', name: 'Scaleback Leggings', profession: 'leatherworking', requiredSkill: 77,
    resultItemId: 'scaleback_leggings', resultQuantity: 1,
    materials: [{ itemId: 'scaleback_leather', quantity: 5 }],
    craftSeconds: 16.5, xpAward: 89,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaleback_boots: {
    id: 'scaleback_boots', name: 'Scaleback Boots', profession: 'leatherworking', requiredSkill: 86,
    resultItemId: 'scaleback_boots', resultQuantity: 1,
    materials: [{ itemId: 'scaleback_leather', quantity: 4 }, { itemId: 'magma_heart', quantity: 1 }],
    craftSeconds: 17.9, xpAward: 101,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaleback_gloves: {
    id: 'scaleback_gloves', name: 'Scaleback Gloves', profession: 'leatherworking', requiredSkill: 73,
    resultItemId: 'scaleback_gloves', resultQuantity: 1,
    materials: [{ itemId: 'scaleback_leather', quantity: 3 }],
    craftSeconds: 15.9, xpAward: 83,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaleback_cap: {
    id: 'scaleback_cap', name: 'Scaleback Cap', profession: 'leatherworking', requiredSkill: 80,
    resultItemId: 'scaleback_cap', resultQuantity: 1,
    materials: [{ itemId: 'scaleback_leather', quantity: 4 }],
    craftSeconds: 17, xpAward: 93,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  charred_robe: {
    id: 'charred_robe', name: 'Charred Robe', profession: 'tailoring', requiredSkill: 21,
    resultItemId: 'charred_robe', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 11.6, xpAward: 35,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  charred_leggings: {
    id: 'charred_leggings', name: 'Charred Leggings', profession: 'tailoring', requiredSkill: 21,
    resultItemId: 'charred_leggings', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 11.6, xpAward: 35,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  charred_gloves: {
    id: 'charred_gloves', name: 'Charred Gloves', profession: 'tailoring', requiredSkill: 20,
    resultItemId: 'charred_gloves', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 3 }],
    craftSeconds: 11.5, xpAward: 34,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  charred_boots: {
    id: 'charred_boots', name: 'Charred Boots', profession: 'tailoring', requiredSkill: 22,
    resultItemId: 'charred_boots', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 4 }],
    craftSeconds: 11.8, xpAward: 37,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  charred_cap: {
    id: 'charred_cap', name: 'Charred Cap', profession: 'tailoring', requiredSkill: 22,
    resultItemId: 'charred_cap', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 4 }],
    craftSeconds: 11.8, xpAward: 37,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  cinderbloom_elixir: {
    id: 'cinderbloom_elixir', name: 'Cinderbloom Elixir', profession: 'alchemy', requiredSkill: 16,
    resultItemId: 'cinderbloom_elixir', resultQuantity: 1,
    materials: [
      { itemId: 'cinderbloom', quantity: 4 },
      { itemId: 'scorchweed', quantity: 2 },
    ],
    craftSeconds: 8, xpAward: 24,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Cinderheart Crater ─────────────────────────────────────────────────
  obsidian_bar: {
    id: 'obsidian_bar', name: 'Obsidian Bar', profession: 'mining', requiredSkill: 48,
    resultItemId: 'obsidian_bar', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_ore', quantity: 1 }],
    craftSeconds: 15, xpAward: 36,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  platinum_bar: {
    id: 'platinum_bar', name: 'Platinum Bar', profession: 'mining', requiredSkill: 48,
    resultItemId: 'platinum_bar', resultQuantity: 1,
    materials: [{ itemId: 'platinum_ore', quantity: 1 }],
    craftSeconds: 15, xpAward: 38,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberscale_leather: {
    id: 'emberscale_leather', name: 'Emberscale Leather', profession: 'leatherworking', requiredSkill: 86,
    resultItemId: 'emberscale_leather', resultQuantity: 1,
    materials: [
      { itemId: 'emberscale_hide', quantity: 5 },
      { itemId: 'emberscale_claw', quantity: 2 },
    ],
    craftSeconds: 17.9, xpAward: 101,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberscale_leggings: {
    id: 'emberscale_leggings', name: 'Emberscale Leggings', profession: 'leatherworking', requiredSkill: 91,
    resultItemId: 'emberscale_leggings', resultQuantity: 1,
    materials: [{ itemId: 'emberscale_leather', quantity: 5 }],
    craftSeconds: 18.6, xpAward: 107,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberscale_boots: {
    id: 'emberscale_boots', name: 'Emberscale Boots', profession: 'leatherworking', requiredSkill: 100,
    resultItemId: 'emberscale_boots', resultQuantity: 1,
    materials: [{ itemId: 'emberscale_leather', quantity: 4 }, { itemId: 'emberlords_ash', quantity: 1 }],
    craftSeconds: 20, xpAward: 120,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberscale_gloves: {
    id: 'emberscale_gloves', name: 'Emberscale Gloves', profession: 'leatherworking', requiredSkill: 87,
    resultItemId: 'emberscale_gloves', resultQuantity: 1,
    materials: [{ itemId: 'emberscale_leather', quantity: 3 }],
    craftSeconds: 18, xpAward: 102,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberscale_cap: {
    id: 'emberscale_cap', name: 'Emberscale Cap', profession: 'leatherworking', requiredSkill: 95,
    resultItemId: 'emberscale_cap', resultQuantity: 1,
    materials: [{ itemId: 'emberscale_leather', quantity: 4 }],
    craftSeconds: 19.2, xpAward: 113,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashenweave_robe: {
    id: 'ashenweave_robe', name: 'Ashenweave Robe', profession: 'tailoring', requiredSkill: 25,
    resultItemId: 'ashenweave_robe', resultQuantity: 1,
    materials: [{ itemId: 'ashenweave_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 12.4, xpAward: 43,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashenweave_leggings: {
    id: 'ashenweave_leggings', name: 'Ashenweave Leggings', profession: 'tailoring', requiredSkill: 25,
    resultItemId: 'ashenweave_leggings', resultQuantity: 1,
    materials: [{ itemId: 'ashenweave_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 12.4, xpAward: 43,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashenweave_gloves: {
    id: 'ashenweave_gloves', name: 'Ashenweave Gloves', profession: 'tailoring', requiredSkill: 24,
    resultItemId: 'ashenweave_gloves', resultQuantity: 1,
    materials: [{ itemId: 'ashenweave_cloth', quantity: 3 }],
    craftSeconds: 12.2, xpAward: 41,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashenweave_cap: {
    id: 'ashenweave_cap', name: 'Ashenweave Cap', profession: 'tailoring', requiredSkill: 26,
    resultItemId: 'ashenweave_cap', resultQuantity: 1,
    materials: [{ itemId: 'ashenweave_cloth', quantity: 4 }],
    craftSeconds: 12.5, xpAward: 45,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashenweave_boots: {
    id: 'ashenweave_boots', name: 'Ashenweave Boots', profession: 'tailoring', requiredSkill: 26,
    resultItemId: 'ashenweave_boots', resultQuantity: 1,
    materials: [{ itemId: 'ashenweave_cloth', quantity: 4 }],
    craftSeconds: 12.5, xpAward: 45,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberheart_potion: {
    id: 'emberheart_potion', name: 'Emberheart Potion', profession: 'alchemy', requiredSkill: 19,
    resultItemId: 'emberheart_potion', resultQuantity: 1,
    materials: [
      { itemId: 'emberheart_bloom', quantity: 4 },
      { itemId: 'heartbloom', quantity: 2 },
    ],
    craftSeconds: 8.4, xpAward: 28,
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Alchemy buff potions — spread across the full 1-300 skill range to
  // actually exercise Journeyman/Expert/Artisan, unlike the pre-overhaul
  // recipe set which topped out around skill 56.
  mana_potion: {
    id: 'mana_potion', name: 'Mana Potion', profession: 'alchemy', requiredSkill: 4,
    resultItemId: 'mana_potion', resultQuantity: 1,
    materials: [{ itemId: 'peacebloom', quantity: 4 }],
    craftSeconds: 6.4, xpAward: 8,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  minor_battle_draught: {
    id: 'minor_battle_draught', name: 'Minor Battle Draught', profession: 'alchemy', requiredSkill: 20,
    resultItemId: 'minor_battle_draught', resultQuantity: 1,
    materials: [{ itemId: 'mountain_sage', quantity: 5 }],
    craftSeconds: 8.5, xpAward: 29,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  minor_stoneskin_draught: {
    id: 'minor_stoneskin_draught', name: 'Minor Stoneskin Draught', profession: 'alchemy', requiredSkill: 25,
    resultItemId: 'minor_stoneskin_draught', resultQuantity: 1,
    materials: [{ itemId: 'mountain_sage', quantity: 6 }],
    craftSeconds: 9.2, xpAward: 34,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  tonic_of_might: {
    id: 'tonic_of_might', name: 'Tonic of Might', profession: 'alchemy', requiredSkill: 35,
    resultItemId: 'tonic_of_might', resultQuantity: 1,
    materials: [{ itemId: 'sunpetal', quantity: 5 }],
    craftSeconds: 10.5, xpAward: 45,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  elixir_of_the_mind: {
    id: 'elixir_of_the_mind', name: 'Elixir of the Mind', profession: 'alchemy', requiredSkill: 39,
    resultItemId: 'elixir_of_the_mind', resultQuantity: 1,
    materials: [{ itemId: 'sunpetal', quantity: 6 }],
    craftSeconds: 11, xpAward: 50,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  draught_of_resistance: {
    id: 'draught_of_resistance', name: 'Draught of Resistance', profession: 'alchemy', requiredSkill: 50,
    resultItemId: 'draught_of_resistance', resultQuantity: 1,
    materials: [{ itemId: 'emberpetal', quantity: 6 }],
    craftSeconds: 12.4, xpAward: 61,
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  potion_of_precision: {
    id: 'potion_of_precision', name: 'Potion of Precision', profession: 'alchemy', requiredSkill: 62,
    resultItemId: 'potion_of_precision', resultQuantity: 1,
    materials: [{ itemId: 'cinderbloom', quantity: 6 }],
    craftSeconds: 14, xpAward: 73,
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  potion_of_evasion: {
    id: 'potion_of_evasion', name: 'Potion of Evasion', profession: 'alchemy', requiredSkill: 66,
    resultItemId: 'potion_of_evasion', resultQuantity: 1,
    materials: [{ itemId: 'cinderbloom', quantity: 7 }],
    craftSeconds: 14.5, xpAward: 76,
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  greater_battle_draught: {
    id: 'greater_battle_draught', name: 'Greater Battle Draught', profession: 'alchemy', requiredSkill: 85,
    resultItemId: 'greater_battle_draught', resultQuantity: 1,
    materials: [{ itemId: 'emberheart_bloom', quantity: 6 }],
    craftSeconds: 17, xpAward: 94,
    source: 'trainer', rarity: 'rare', learnedAutomatically: true,
  },
  greater_stoneskin_draught: {
    id: 'greater_stoneskin_draught', name: 'Greater Stoneskin Draught', profession: 'alchemy', requiredSkill: 100,
    resultItemId: 'greater_stoneskin_draught', resultQuantity: 1,
    materials: [{ itemId: 'emberheart_bloom', quantity: 8 }],
    craftSeconds: 19, xpAward: 107,
    source: 'trainer', rarity: 'rare', learnedAutomatically: true,
  },

  // ── Cooking — rebuilt onto craftingEngine.ts's shared 1-100 curve
  // (calibrated to ~32h active crafting time to level 100, same
  // methodology as every other crafting profession — see the session's
  // design notes). Four categories per the design brief: Basic Food (cheap,
  // pure heal, no buff — roasted_boar_meat/hunters_jerky), Stat Food (the
  // original 6 single-fish dishes, rescaled), Combination Meals (fish +
  // monster drops + herbs/seasoning together — strictly better buffs than
  // any single-source dish at the same level, per the brief's own "Wolf &
  // Trout Stew"/"Hunter's Seafood Feast" examples), and Feasts (high-level,
  // multi-source, bigger duration/buffs, a real material sink). Draws
  // ingredients from Fishing (brook_trout..emberheart_koi), combat drops
  // (boar_meat/raw_meat and the new scavenger_meat/hound_meat/drake_meat/
  // behemoth_flank/pyraxis_flank/common_seasoning/rare_seasoning — see
  // monsters.ts), AND Herbalism (wildroot) in the two feasts, so Cooking
  // draws from several systems rather than having its own dedicated
  // gathering profession, exactly as the brief specifies.
  farmhouse_stew: {
    id: 'farmhouse_stew', name: 'Farmhouse Stew', profession: 'cooking', requiredSkill: 1,
    resultItemId: 'farmhouse_stew', resultQuantity: 1,
    materials: [{ itemId: 'brook_trout', quantity: 3 }],
    craftSeconds: 6, xpAward: 2,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  roasted_boar_meat: {
    id: 'roasted_boar_meat', name: 'Roasted Boar Meat', profession: 'cooking', requiredSkill: 1,
    resultItemId: 'roasted_boar_meat', resultQuantity: 1,
    materials: [{ itemId: 'boar_meat', quantity: 3 }],
    craftSeconds: 6, xpAward: 2,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  wolf_trout_stew: {
    id: 'wolf_trout_stew', name: 'Wolf & Trout Stew', profession: 'cooking', requiredSkill: 10,
    resultItemId: 'wolf_trout_stew', resultQuantity: 1,
    materials: [
      { itemId: 'brook_trout', quantity: 2 },
      { itemId: 'raw_meat', quantity: 1 },
      { itemId: 'wildroot', quantity: 1 },
    ],
    craftSeconds: 7.2, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  highland_roast: {
    id: 'highland_roast', name: 'Highland Roast', profession: 'cooking', requiredSkill: 20,
    resultItemId: 'highland_roast', resultQuantity: 1,
    materials: [{ itemId: 'mountain_char', quantity: 4 }],
    craftSeconds: 8.5, xpAward: 29,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  hunters_jerky: {
    id: 'hunters_jerky', name: 'Hunter’s Jerky', profession: 'cooking', requiredSkill: 25,
    resultItemId: 'hunters_jerky', resultQuantity: 1,
    materials: [{ itemId: 'raw_meat', quantity: 4 }],
    craftSeconds: 9.2, xpAward: 34,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  spiced_trail_soup: {
    id: 'spiced_trail_soup', name: 'Spiced Trail Soup', profession: 'cooking', requiredSkill: 32,
    resultItemId: 'spiced_trail_soup', resultQuantity: 1,
    materials: [
      { itemId: 'mountain_char', quantity: 2 },
      { itemId: 'raw_meat', quantity: 1 },
      { itemId: 'common_seasoning', quantity: 1 },
    ],
    craftSeconds: 10.1, xpAward: 42,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  embercured_fillet: {
    id: 'embercured_fillet', name: 'Embercured Fillet', profession: 'cooking', requiredSkill: 39,
    resultItemId: 'embercured_fillet', resultQuantity: 1,
    materials: [{ itemId: 'ember_eel', quantity: 4 }],
    craftSeconds: 11, xpAward: 50,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scavengers_broth: {
    id: 'scavengers_broth', name: 'Scavenger’s Broth', profession: 'cooking', requiredSkill: 48,
    resultItemId: 'scavengers_broth', resultQuantity: 1,
    materials: [
      { itemId: 'ember_eel', quantity: 2 },
      { itemId: 'scavenger_meat', quantity: 1 },
    ],
    craftSeconds: 12.2, xpAward: 59,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  charred_skewer: {
    id: 'charred_skewer', name: 'Charred Skewer', profession: 'cooking', requiredSkill: 55,
    resultItemId: 'charred_skewer', resultQuantity: 1,
    materials: [
      { itemId: 'ashfin_carp', quantity: 2 },
      { itemId: 'hound_meat', quantity: 1 },
    ],
    craftSeconds: 13.1, xpAward: 66,
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  ashfin_chowder: {
    id: 'ashfin_chowder', name: 'Ashfin Chowder', profession: 'cooking', requiredSkill: 58,
    resultItemId: 'ashfin_chowder', resultQuantity: 1,
    materials: [{ itemId: 'ashfin_carp', quantity: 5 }],
    craftSeconds: 13.5, xpAward: 69,
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  hunters_seafood_feast: {
    id: 'hunters_seafood_feast', name: 'Hunter’s Seafood Feast', profession: 'cooking', requiredSkill: 65,
    resultItemId: 'hunters_seafood_feast', resultQuantity: 1,
    materials: [
      { itemId: 'magma_darter', quantity: 2 },
      { itemId: 'hound_meat', quantity: 2 },
      { itemId: 'common_seasoning', quantity: 1 },
    ],
    craftSeconds: 14.4, xpAward: 75,
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  drake_meat_platter: {
    id: 'drake_meat_platter', name: 'Drake Meat Platter', profession: 'cooking', requiredSkill: 72,
    resultItemId: 'drake_meat_platter', resultQuantity: 1,
    materials: [
      { itemId: 'drake_meat', quantity: 2 },
      { itemId: 'magma_darter', quantity: 1 },
    ],
    craftSeconds: 15.3, xpAward: 82,
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  magma_darter_skewers: {
    id: 'magma_darter_skewers', name: 'Magma Darter Skewers', profession: 'cooking', requiredSkill: 77,
    resultItemId: 'magma_darter_skewers', resultQuantity: 1,
    materials: [{ itemId: 'magma_darter', quantity: 5 }],
    craftSeconds: 16, xpAward: 87,
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  behemoth_feast: {
    id: 'behemoth_feast', name: 'Behemoth Feast', profession: 'cooking', requiredSkill: 88,
    resultItemId: 'behemoth_feast', resultQuantity: 1,
    materials: [
      { itemId: 'behemoth_flank', quantity: 3 },
      { itemId: 'magma_darter', quantity: 4 },
      { itemId: 'rare_seasoning', quantity: 2 },
    ],
    craftSeconds: 17.4, xpAward: 97,
    source: 'trainer', rarity: 'rare', learnedAutomatically: true,
  },
  // Deliberately requires 10 low-level brook_trout alongside high-level
  // fish and meat — per the design brief's "Master Fisherman's Feast"
  // example, keeping demand for beginner materials alive at the endgame.
  master_fishermans_feast: {
    id: 'master_fishermans_feast', name: 'Master Fisherman’s Feast', profession: 'cooking', requiredSkill: 95,
    resultItemId: 'master_fishermans_feast', resultQuantity: 1,
    materials: [
      { itemId: 'emberheart_koi', quantity: 5 },
      { itemId: 'brook_trout', quantity: 10 },
      { itemId: 'drake_meat', quantity: 3 },
      { itemId: 'wildroot', quantity: 2 },
    ],
    craftSeconds: 18.3, xpAward: 103,
    source: 'trainer', rarity: 'rare', learnedAutomatically: true,
  },
  emberheart_feast: {
    id: 'emberheart_feast', name: 'Emberheart Feast', profession: 'cooking', requiredSkill: 100,
    resultItemId: 'emberheart_feast', resultQuantity: 1,
    materials: [{ itemId: 'emberheart_koi', quantity: 6 }],
    craftSeconds: 19, xpAward: 107,
    source: 'trainer', rarity: 'rare', learnedAutomatically: true,
  },
  // Rare: taught only by Recipe: Pyraxis Flame-Seared Flank (a rare drop
  // from Pyraxis itself — see monsters.ts), matching the design brief's
  // explicit "a boss might drop the recipe, but the ingredients still need
  // to be gathered separately" example almost exactly.
  pyraxis_flame_seared_flank: {
    id: 'pyraxis_flame_seared_flank', name: 'Pyraxis Flame-Seared Flank', profession: 'cooking', requiredSkill: 100,
    resultItemId: 'pyraxis_flame_seared_flank', resultQuantity: 1,
    materials: [
      { itemId: 'pyraxis_flank', quantity: 1 },
      { itemId: 'emberheart_koi', quantity: 2 },
      { itemId: 'rare_seasoning', quantity: 1 },
    ],
    craftSeconds: 19, xpAward: 107,
    source: 'dungeon_drop', rarity: 'rare', learnedAutomatically: false,
  },

  // ── Tailoring bags — permanent inventory capacity (see items.ts).
  small_pack: {
    id: 'small_pack', name: 'Small Pack', profession: 'tailoring', requiredSkill: 5,
    resultItemId: 'small_pack', resultQuantity: 1,
    materials: [{ itemId: 'linen_cloth', quantity: 6 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 8.7, xpAward: 7,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  travelers_pack: {
    id: 'travelers_pack', name: "Traveler's Pack", profession: 'tailoring', requiredSkill: 30,
    resultItemId: 'travelers_pack', resultQuantity: 1,
    materials: [{ itemId: 'heavy_cloth', quantity: 6 }, { itemId: 'simple_thread', quantity: 3 }],
    craftSeconds: 13.3, xpAward: 53,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  explorers_pack: {
    id: 'explorers_pack', name: "Explorer's Pack", profession: 'tailoring', requiredSkill: 65,
    resultItemId: 'explorers_pack', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 6 }, { itemId: 'simple_thread', quantity: 3 }],
    craftSeconds: 19.6, xpAward: 130,
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  dwarven_rucksack: {
    id: 'dwarven_rucksack', name: 'Dwarven Rucksack', profession: 'tailoring', requiredSkill: 100,
    resultItemId: 'dwarven_rucksack', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 6 }, { itemId: 'simple_thread', quantity: 4 }],
    craftSeconds: 26, xpAward: 213,
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },

  // ── Blacksmith repairs — converts a damaged dungeon boss drop into its
  // real, equippable form. An ordinary Recipe (materials in, item out),
  // not a bespoke repair system — see items.ts's "_damaged" convention
  // and gameData/types.ts's ItemDef.repairsIntoItemId. requiredSkill
  // scales with the drop's own tier, keeping Blacksmithing relevant deep
  // into Expert/Artisan rather than just the early game.
  repair_overseers_greatmace: {
    id: 'repair_overseers_greatmace', name: "Repair Overseer's Greatmace", profession: 'smithing', requiredSkill: 54,
    resultItemId: 'overseers_greatmace', resultQuantity: 1,
    materials: [{ itemId: 'overseers_greatmace_damaged', quantity: 1 }, { itemId: 'mithril_ore', quantity: 5 }],
    goldCost: 300,
    craftSeconds: 17.6, xpAward: 110,
    source: 'dungeon_drop', rarity: 'rare', learnedAutomatically: true,
  },
  repair_pyraxis_warblade: {
    id: 'repair_pyraxis_warblade', name: "Repair Pyraxis's Warblade", profession: 'smithing', requiredSkill: 100,
    resultItemId: 'pyraxis_warblade', resultQuantity: 1,
    materials: [{ itemId: 'pyraxis_warblade_damaged', quantity: 1 }, { itemId: 'obsidian_ore', quantity: 8 }],
    goldCost: 800,
    craftSeconds: 26, xpAward: 223,
    source: 'dungeon_drop', rarity: 'rare', learnedAutomatically: true,
  },

  // ── Taught only by Formula: Emberforged Gauntlets (quests.ts's "The Lost
  // Forge" chain) — not obtainable just by reaching the skill requirement.
  emberforged_gauntlets_recipe: {
    id: 'emberforged_gauntlets_recipe', name: 'Emberforged Gauntlets', profession: 'smithing', requiredSkill: 69,
    resultItemId: 'emberforged_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_ore', quantity: 8 }, { itemId: 'arcane_essence', quantity: 2 }],
    craftSeconds: 20.4, xpAward: 146,
    source: 'profession_quest', rarity: 'rare', learnedAutomatically: false,
  },

  // ── Blacksmithing full armor sets (Mining/Smithing Mastery-pilot overhaul) ──
  // See items.ts's matching section's doc comment — same generated-content
  // posture, 124 recipes mirroring the 124 new items 1:1 by id.
  copper_helm: {
    id: 'copper_helm', name: 'Copper Helm', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'copper_helm', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 3 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_copper_helm: {
    id: 'sacred_copper_helm', name: 'Sacred Copper Helm', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'sacred_copper_helm', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 3 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  copper_chestplate: {
    id: 'copper_chestplate', name: 'Copper Chestplate', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'copper_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 5 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_copper_chestplate: {
    id: 'sacred_copper_chestplate', name: 'Sacred Copper Chestplate', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'sacred_copper_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 5 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  copper_gauntlets: {
    id: 'copper_gauntlets', name: 'Copper Gauntlets', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'copper_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 3 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_copper_gauntlets: {
    id: 'sacred_copper_gauntlets', name: 'Sacred Copper Gauntlets', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'sacred_copper_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 3 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  copper_legplates: {
    id: 'copper_legplates', name: 'Copper Legplates', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'copper_legplates', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 4 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_copper_legplates: {
    id: 'sacred_copper_legplates', name: 'Sacred Copper Legplates', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'sacred_copper_legplates', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 4 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  copper_greaves: {
    id: 'copper_greaves', name: 'Copper Greaves', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'copper_greaves', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 3 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_copper_greaves: {
    id: 'sacred_copper_greaves', name: 'Sacred Copper Greaves', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'sacred_copper_greaves', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 3 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  copper_shield: {
    id: 'copper_shield', name: 'Copper Shield', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'copper_shield', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 4 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_copper_shield: {
    id: 'sacred_copper_shield', name: 'Sacred Copper Shield', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'sacred_copper_shield', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 4 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  copper_sword: {
    id: 'copper_sword', name: 'Copper Sword', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'copper_sword', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 4 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_copper_sword: {
    id: 'sacred_copper_sword', name: 'Sacred Copper Sword', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'sacred_copper_sword', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 4 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  copper_battleaxe: {
    id: 'copper_battleaxe', name: 'Copper Battleaxe', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'copper_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 6 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_copper_battleaxe: {
    id: 'sacred_copper_battleaxe', name: 'Sacred Copper Battleaxe', profession: 'smithing', requiredSkill: 1,
    resultItemId: 'sacred_copper_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 6 }],
    craftSeconds: 8, xpAward: 1,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  bronze_helm: {
    id: 'bronze_helm', name: 'Bronze Helm', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'bronze_helm', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 3 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_bronze_helm: {
    id: 'sacred_bronze_helm', name: 'Sacred Bronze Helm', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'sacred_bronze_helm', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 3 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  bronze_chestplate: {
    id: 'bronze_chestplate', name: 'Bronze Chestplate', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'bronze_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 5 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_bronze_chestplate: {
    id: 'sacred_bronze_chestplate', name: 'Sacred Bronze Chestplate', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'sacred_bronze_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 5 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  bronze_gauntlets: {
    id: 'bronze_gauntlets', name: 'Bronze Gauntlets', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'bronze_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 3 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_bronze_gauntlets: {
    id: 'sacred_bronze_gauntlets', name: 'Sacred Bronze Gauntlets', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'sacred_bronze_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 3 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  bronze_legplates: {
    id: 'bronze_legplates', name: 'Bronze Legplates', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'bronze_legplates', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 4 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_bronze_legplates: {
    id: 'sacred_bronze_legplates', name: 'Sacred Bronze Legplates', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'sacred_bronze_legplates', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 4 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  bronze_greaves: {
    id: 'bronze_greaves', name: 'Bronze Greaves', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'bronze_greaves', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 3 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_bronze_greaves: {
    id: 'sacred_bronze_greaves', name: 'Sacred Bronze Greaves', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'sacred_bronze_greaves', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 3 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  bronze_shield: {
    id: 'bronze_shield', name: 'Bronze Shield', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'bronze_shield', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 4 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_bronze_shield: {
    id: 'sacred_bronze_shield', name: 'Sacred Bronze Shield', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'sacred_bronze_shield', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 4 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  bronze_sword: {
    id: 'bronze_sword', name: 'Bronze Sword', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'bronze_sword', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 4 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_bronze_sword: {
    id: 'sacred_bronze_sword', name: 'Sacred Bronze Sword', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'sacred_bronze_sword', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 4 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  bronze_battleaxe: {
    id: 'bronze_battleaxe', name: 'Bronze Battleaxe', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'bronze_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 6 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_bronze_battleaxe: {
    id: 'sacred_bronze_battleaxe', name: 'Sacred Bronze Battleaxe', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'sacred_bronze_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 6 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  iron_helm: {
    id: 'iron_helm', name: 'Iron Helm', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'iron_helm', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 3 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_iron_helm: {
    id: 'sacred_iron_helm', name: 'Sacred Iron Helm', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'sacred_iron_helm', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 3 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  iron_chestplate: {
    id: 'iron_chestplate', name: 'Iron Chestplate', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'iron_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 5 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_iron_chestplate: {
    id: 'sacred_iron_chestplate', name: 'Sacred Iron Chestplate', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'sacred_iron_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 5 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  iron_gauntlets: {
    id: 'iron_gauntlets', name: 'Iron Gauntlets', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'iron_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 3 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_iron_gauntlets: {
    id: 'sacred_iron_gauntlets', name: 'Sacred Iron Gauntlets', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'sacred_iron_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 3 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  iron_legplates: {
    id: 'iron_legplates', name: 'Iron Legplates', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'iron_legplates', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 4 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_iron_legplates: {
    id: 'sacred_iron_legplates', name: 'Sacred Iron Legplates', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'sacred_iron_legplates', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 4 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  iron_greaves: {
    id: 'iron_greaves', name: 'Iron Greaves', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'iron_greaves', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 3 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_iron_greaves: {
    id: 'sacred_iron_greaves', name: 'Sacred Iron Greaves', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'sacred_iron_greaves', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 3 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  iron_shield: {
    id: 'iron_shield', name: 'Iron Shield', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'iron_shield', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 4 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_iron_shield: {
    id: 'sacred_iron_shield', name: 'Sacred Iron Shield', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'sacred_iron_shield', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 4 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  iron_sword: {
    id: 'iron_sword', name: 'Iron Sword', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'iron_sword', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 4 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_iron_sword: {
    id: 'sacred_iron_sword', name: 'Sacred Iron Sword', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'sacred_iron_sword', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 4 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  iron_battleaxe: {
    id: 'iron_battleaxe', name: 'Iron Battleaxe', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'iron_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 6 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_iron_battleaxe: {
    id: 'sacred_iron_battleaxe', name: 'Sacred Iron Battleaxe', profession: 'smithing', requiredSkill: 10,
    resultItemId: 'sacred_iron_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 6 }],
    craftSeconds: 9.6, xpAward: 16,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  steel_helm: {
    id: 'steel_helm', name: 'Steel Helm', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'steel_helm', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 3 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_steel_helm: {
    id: 'sacred_steel_helm', name: 'Sacred Steel Helm', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'sacred_steel_helm', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 3 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  steel_chestplate: {
    id: 'steel_chestplate', name: 'Steel Chestplate', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'steel_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 5 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_steel_chestplate: {
    id: 'sacred_steel_chestplate', name: 'Sacred Steel Chestplate', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'sacred_steel_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 5 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  steel_gauntlets: {
    id: 'steel_gauntlets', name: 'Steel Gauntlets', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'steel_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 3 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_steel_gauntlets: {
    id: 'sacred_steel_gauntlets', name: 'Sacred Steel Gauntlets', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'sacred_steel_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 3 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  steel_legplates: {
    id: 'steel_legplates', name: 'Steel Legplates', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'steel_legplates', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 4 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_steel_legplates: {
    id: 'sacred_steel_legplates', name: 'Sacred Steel Legplates', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'sacred_steel_legplates', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 4 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  steel_greaves: {
    id: 'steel_greaves', name: 'Steel Greaves', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'steel_greaves', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 3 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_steel_greaves: {
    id: 'sacred_steel_greaves', name: 'Sacred Steel Greaves', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'sacred_steel_greaves', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 3 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  steel_shield: {
    id: 'steel_shield', name: 'Steel Shield', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'steel_shield', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 4 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_steel_shield: {
    id: 'sacred_steel_shield', name: 'Sacred Steel Shield', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'sacred_steel_shield', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 4 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  steel_sword: {
    id: 'steel_sword', name: 'Steel Sword', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'steel_sword', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 4 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_steel_sword: {
    id: 'sacred_steel_sword', name: 'Sacred Steel Sword', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'sacred_steel_sword', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 4 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  steel_battleaxe: {
    id: 'steel_battleaxe', name: 'Steel Battleaxe', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'steel_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 6 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_steel_battleaxe: {
    id: 'sacred_steel_battleaxe', name: 'Sacred Steel Battleaxe', profession: 'smithing', requiredSkill: 11,
    resultItemId: 'sacred_steel_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'steel_bar', quantity: 6 }],
    craftSeconds: 9.8, xpAward: 18,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  mithril_helm: {
    id: 'mithril_helm', name: 'Mithril Helm', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'mithril_helm', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 3 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_mithril_helm: {
    id: 'sacred_mithril_helm', name: 'Sacred Mithril Helm', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'sacred_mithril_helm', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 3 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  mithril_chestplate: {
    id: 'mithril_chestplate', name: 'Mithril Chestplate', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'mithril_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 5 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_mithril_chestplate: {
    id: 'sacred_mithril_chestplate', name: 'Sacred Mithril Chestplate', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'sacred_mithril_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 5 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  mithril_gauntlets: {
    id: 'mithril_gauntlets', name: 'Mithril Gauntlets', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'mithril_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 3 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_mithril_gauntlets: {
    id: 'sacred_mithril_gauntlets', name: 'Sacred Mithril Gauntlets', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'sacred_mithril_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 3 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  mithril_legplates: {
    id: 'mithril_legplates', name: 'Mithril Legplates', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'mithril_legplates', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 4 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_mithril_legplates: {
    id: 'sacred_mithril_legplates', name: 'Sacred Mithril Legplates', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'sacred_mithril_legplates', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 4 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  mithril_greaves: {
    id: 'mithril_greaves', name: 'Mithril Greaves', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'mithril_greaves', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 3 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_mithril_greaves: {
    id: 'sacred_mithril_greaves', name: 'Sacred Mithril Greaves', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'sacred_mithril_greaves', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 3 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  mithril_shield: {
    id: 'mithril_shield', name: 'Mithril Shield', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'mithril_shield', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 4 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_mithril_shield: {
    id: 'sacred_mithril_shield', name: 'Sacred Mithril Shield', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'sacred_mithril_shield', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 4 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  mithril_sword: {
    id: 'mithril_sword', name: 'Mithril Sword', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'mithril_sword', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 4 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_mithril_sword: {
    id: 'sacred_mithril_sword', name: 'Sacred Mithril Sword', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'sacred_mithril_sword', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 4 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  mithril_battleaxe: {
    id: 'mithril_battleaxe', name: 'Mithril Battleaxe', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'mithril_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 6 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_mithril_battleaxe: {
    id: 'sacred_mithril_battleaxe', name: 'Sacred Mithril Battleaxe', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'sacred_mithril_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'mithril_bar', quantity: 6 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  thorium_helm: {
    id: 'thorium_helm', name: 'Thorium Helm', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'thorium_helm', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 3 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_thorium_helm: {
    id: 'sacred_thorium_helm', name: 'Sacred Thorium Helm', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'sacred_thorium_helm', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 3 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  thorium_chestplate: {
    id: 'thorium_chestplate', name: 'Thorium Chestplate', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'thorium_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 5 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_thorium_chestplate: {
    id: 'sacred_thorium_chestplate', name: 'Sacred Thorium Chestplate', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'sacred_thorium_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 5 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  thorium_gauntlets: {
    id: 'thorium_gauntlets', name: 'Thorium Gauntlets', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'thorium_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 3 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_thorium_gauntlets: {
    id: 'sacred_thorium_gauntlets', name: 'Sacred Thorium Gauntlets', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'sacred_thorium_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 3 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  thorium_legplates: {
    id: 'thorium_legplates', name: 'Thorium Legplates', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'thorium_legplates', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 4 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_thorium_legplates: {
    id: 'sacred_thorium_legplates', name: 'Sacred Thorium Legplates', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'sacred_thorium_legplates', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 4 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  thorium_greaves: {
    id: 'thorium_greaves', name: 'Thorium Greaves', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'thorium_greaves', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 3 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_thorium_greaves: {
    id: 'sacred_thorium_greaves', name: 'Sacred Thorium Greaves', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'sacred_thorium_greaves', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 3 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  thorium_shield: {
    id: 'thorium_shield', name: 'Thorium Shield', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'thorium_shield', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 4 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_thorium_shield: {
    id: 'sacred_thorium_shield', name: 'Sacred Thorium Shield', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'sacred_thorium_shield', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 4 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  thorium_sword: {
    id: 'thorium_sword', name: 'Thorium Sword', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'thorium_sword', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 4 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_thorium_sword: {
    id: 'sacred_thorium_sword', name: 'Sacred Thorium Sword', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'sacred_thorium_sword', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 4 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  thorium_battleaxe: {
    id: 'thorium_battleaxe', name: 'Thorium Battleaxe', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'thorium_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 6 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_thorium_battleaxe: {
    id: 'sacred_thorium_battleaxe', name: 'Sacred Thorium Battleaxe', profession: 'smithing', requiredSkill: 16,
    resultItemId: 'sacred_thorium_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'thorium_bar', quantity: 6 }],
    craftSeconds: 10.7, xpAward: 27,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  obsidian_helm: {
    id: 'obsidian_helm', name: 'Obsidian Helm', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'obsidian_helm', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 3 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_obsidian_helm: {
    id: 'sacred_obsidian_helm', name: 'Sacred Obsidian Helm', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'sacred_obsidian_helm', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 3 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  obsidian_chestplate: {
    id: 'obsidian_chestplate', name: 'Obsidian Chestplate', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'obsidian_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 5 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_obsidian_chestplate: {
    id: 'sacred_obsidian_chestplate', name: 'Sacred Obsidian Chestplate', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'sacred_obsidian_chestplate', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 5 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  obsidian_gauntlets: {
    id: 'obsidian_gauntlets', name: 'Obsidian Gauntlets', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'obsidian_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 3 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_obsidian_gauntlets: {
    id: 'sacred_obsidian_gauntlets', name: 'Sacred Obsidian Gauntlets', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'sacred_obsidian_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 3 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  obsidian_legplates: {
    id: 'obsidian_legplates', name: 'Obsidian Legplates', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'obsidian_legplates', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 4 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_obsidian_legplates: {
    id: 'sacred_obsidian_legplates', name: 'Sacred Obsidian Legplates', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'sacred_obsidian_legplates', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 4 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  obsidian_greaves: {
    id: 'obsidian_greaves', name: 'Obsidian Greaves', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'obsidian_greaves', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 3 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_obsidian_greaves: {
    id: 'sacred_obsidian_greaves', name: 'Sacred Obsidian Greaves', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'sacred_obsidian_greaves', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 3 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  obsidian_shield: {
    id: 'obsidian_shield', name: 'Obsidian Shield', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'obsidian_shield', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 4 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_obsidian_shield: {
    id: 'sacred_obsidian_shield', name: 'Sacred Obsidian Shield', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'sacred_obsidian_shield', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 4 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  obsidian_sword: {
    id: 'obsidian_sword', name: 'Obsidian Sword', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'obsidian_sword', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 4 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_obsidian_sword: {
    id: 'sacred_obsidian_sword', name: 'Sacred Obsidian Sword', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'sacred_obsidian_sword', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 4 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  obsidian_battleaxe: {
    id: 'obsidian_battleaxe', name: 'Obsidian Battleaxe', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'obsidian_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 6 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_obsidian_battleaxe: {
    id: 'sacred_obsidian_battleaxe', name: 'Sacred Obsidian Battleaxe', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'sacred_obsidian_battleaxe', resultQuantity: 1,
    materials: [{ itemId: 'obsidian_bar', quantity: 6 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  silver_necklace: {
    id: 'silver_necklace', name: 'Silver Necklace', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'silver_necklace', resultQuantity: 1,
    materials: [{ itemId: 'silver_bar', quantity: 2 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_silver_necklace: {
    id: 'sacred_silver_necklace', name: 'Sacred Silver Necklace', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'sacred_silver_necklace', resultQuantity: 1,
    materials: [{ itemId: 'silver_bar', quantity: 2 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  silver_ring: {
    id: 'silver_ring', name: 'Silver Ring', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'silver_ring', resultQuantity: 1,
    materials: [{ itemId: 'silver_bar', quantity: 2 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_silver_ring: {
    id: 'sacred_silver_ring', name: 'Sacred Silver Ring', profession: 'smithing', requiredSkill: 4,
    resultItemId: 'sacred_silver_ring', resultQuantity: 1,
    materials: [{ itemId: 'silver_bar', quantity: 2 }],
    craftSeconds: 8.5, xpAward: 6,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  gold_necklace: {
    id: 'gold_necklace', name: 'Gold Necklace', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'gold_necklace', resultQuantity: 1,
    materials: [{ itemId: 'gold_bar', quantity: 2 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_gold_necklace: {
    id: 'sacred_gold_necklace', name: 'Sacred Gold Necklace', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'sacred_gold_necklace', resultQuantity: 1,
    materials: [{ itemId: 'gold_bar', quantity: 2 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  gold_ring: {
    id: 'gold_ring', name: 'Gold Ring', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'gold_ring', resultQuantity: 1,
    materials: [{ itemId: 'gold_bar', quantity: 2 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_gold_ring: {
    id: 'sacred_gold_ring', name: 'Sacred Gold Ring', profession: 'smithing', requiredSkill: 12,
    resultItemId: 'sacred_gold_ring', resultQuantity: 1,
    materials: [{ itemId: 'gold_bar', quantity: 2 }],
    craftSeconds: 10, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  platinum_necklace: {
    id: 'platinum_necklace', name: 'Platinum Necklace', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'platinum_necklace', resultQuantity: 1,
    materials: [{ itemId: 'platinum_bar', quantity: 2 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_platinum_necklace: {
    id: 'sacred_platinum_necklace', name: 'Sacred Platinum Necklace', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'sacred_platinum_necklace', resultQuantity: 1,
    materials: [{ itemId: 'platinum_bar', quantity: 2 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  platinum_ring: {
    id: 'platinum_ring', name: 'Platinum Ring', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'platinum_ring', resultQuantity: 1,
    materials: [{ itemId: 'platinum_bar', quantity: 2 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  sacred_platinum_ring: {
    id: 'sacred_platinum_ring', name: 'Sacred Platinum Ring', profession: 'smithing', requiredSkill: 19,
    resultItemId: 'sacred_platinum_ring', resultQuantity: 1,
    materials: [{ itemId: 'platinum_bar', quantity: 2 }],
    craftSeconds: 11.3, xpAward: 33,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },

  // ── Enchanting scrolls — Enchanting's actual crafting recipes (see
  // gameData/enchanting.ts's module doc comment: ENCHANTS is now purely the
  // effect, these recipes own requiredSkill/xpAward/materials/goldCost, same
  // split every other profession already has between its Recipe and its
  // result item). craftSeconds is a smooth linear function of requiredSkill
  // (12-38s across 1-100, same monotonic-float convention the other sparse
  // crafting professions use — see craftingEngine.ts's module doc comment)
  // calibrated by simulation to land Enchanting at ~39 hours to level 100
  // with zero anti-exploit violations, matching its original ~40h target.
  scroll_weapon_minor_might: {
    id: 'scroll_weapon_minor_might', name: 'Scroll: Minor Might', profession: 'enchanting', requiredSkill: 5,
    resultItemId: 'scroll_weapon_minor_might', resultQuantity: 1,
    materials: [{ itemId: 'arcane_dust', quantity: 4 }], goldCost: 5,
    craftSeconds: 13.1, xpAward: 13,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_weapon_greater_might: {
    id: 'scroll_weapon_greater_might', name: 'Scroll: Greater Might', profession: 'enchanting', requiredSkill: 49,
    resultItemId: 'scroll_weapon_greater_might', resultQuantity: 1,
    materials: [{ itemId: 'arcane_essence', quantity: 4 }], goldCost: 25,
    craftSeconds: 24.6, xpAward: 106,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_weapon_superior_might: {
    id: 'scroll_weapon_superior_might', name: 'Scroll: Superior Might', profession: 'enchanting', requiredSkill: 98,
    resultItemId: 'scroll_weapon_superior_might', resultQuantity: 1,
    materials: [{ itemId: 'arcane_crystal', quantity: 3 }], goldCost: 80,
    craftSeconds: 37.5, xpAward: 202,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_chest_minor_stats: {
    id: 'scroll_chest_minor_stats', name: 'Scroll: Minor Vigor', profession: 'enchanting', requiredSkill: 3,
    resultItemId: 'scroll_chest_minor_stats', resultQuantity: 1,
    materials: [{ itemId: 'arcane_dust', quantity: 4 }], goldCost: 5,
    craftSeconds: 12.5, xpAward: 8,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_chest_greater_stats: {
    id: 'scroll_chest_greater_stats', name: 'Scroll: Greater Vigor', profession: 'enchanting', requiredSkill: 52,
    resultItemId: 'scroll_chest_greater_stats', resultQuantity: 1,
    materials: [{ itemId: 'arcane_essence', quantity: 4 }], goldCost: 25,
    craftSeconds: 25.4, xpAward: 112,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_chest_superior_stats: {
    id: 'scroll_chest_superior_stats', name: 'Scroll: Superior Vigor', profession: 'enchanting', requiredSkill: 100,
    resultItemId: 'scroll_chest_superior_stats', resultQuantity: 1,
    materials: [{ itemId: 'arcane_crystal', quantity: 3 }], goldCost: 80,
    craftSeconds: 38, xpAward: 206,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_gloves_minor_focus: {
    id: 'scroll_gloves_minor_focus', name: 'Scroll: Minor Focus', profession: 'enchanting', requiredSkill: 8,
    resultItemId: 'scroll_gloves_minor_focus', resultQuantity: 1,
    materials: [{ itemId: 'arcane_dust', quantity: 3 }], goldCost: 5,
    craftSeconds: 13.8, xpAward: 20,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_gloves_greater_focus: {
    id: 'scroll_gloves_greater_focus', name: 'Scroll: Greater Focus', profession: 'enchanting', requiredSkill: 56,
    resultItemId: 'scroll_gloves_greater_focus', resultQuantity: 1,
    materials: [{ itemId: 'arcane_essence', quantity: 3 }], goldCost: 25,
    craftSeconds: 26.4, xpAward: 120,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_legs_minor_vitality: {
    id: 'scroll_legs_minor_vitality', name: 'Scroll: Minor Vitality', profession: 'enchanting', requiredSkill: 10,
    resultItemId: 'scroll_legs_minor_vitality', resultQuantity: 1,
    materials: [{ itemId: 'arcane_dust', quantity: 4 }], goldCost: 6,
    craftSeconds: 14.4, xpAward: 24,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_legs_greater_vitality: {
    id: 'scroll_legs_greater_vitality', name: 'Scroll: Greater Vitality', profession: 'enchanting', requiredSkill: 63,
    resultItemId: 'scroll_legs_greater_vitality', resultQuantity: 1,
    materials: [{ itemId: 'arcane_essence', quantity: 4 }], goldCost: 28,
    craftSeconds: 28.3, xpAward: 134,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_boots_minor_spirit: {
    id: 'scroll_boots_minor_spirit', name: 'Scroll: Minor Spirit', profession: 'enchanting', requiredSkill: 1,
    resultItemId: 'scroll_boots_minor_spirit', resultQuantity: 1,
    materials: [{ itemId: 'arcane_dust', quantity: 3 }], goldCost: 4,
    craftSeconds: 12, xpAward: 3,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_boots_greater_spirit: {
    id: 'scroll_boots_greater_spirit', name: 'Scroll: Greater Spirit', profession: 'enchanting', requiredSkill: 45,
    resultItemId: 'scroll_boots_greater_spirit', resultQuantity: 1,
    materials: [{ itemId: 'arcane_essence', quantity: 3 }], goldCost: 22,
    craftSeconds: 23.6, xpAward: 98,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_ring_minor_power: {
    id: 'scroll_ring_minor_power', name: 'Scroll: Minor Power', profession: 'enchanting', requiredSkill: 16,
    resultItemId: 'scroll_ring_minor_power', resultQuantity: 1,
    materials: [{ itemId: 'arcane_essence', quantity: 2 }], goldCost: 15,
    craftSeconds: 15.9, xpAward: 37,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  scroll_ring_greater_power: {
    id: 'scroll_ring_greater_power', name: 'Scroll: Greater Power', profession: 'enchanting', requiredSkill: 76,
    resultItemId: 'scroll_ring_greater_power', resultQuantity: 1,
    materials: [{ itemId: 'arcane_crystal', quantity: 2 }], goldCost: 60,
    craftSeconds: 31.7, xpAward: 159,
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
};
