import type { Recipe } from './types';

export const RECIPES: Record<string, Recipe> = {
  light_leather: {
    id: 'light_leather',
    name: 'Light Leather',
    profession: 'leatherworking',
    requiredSkill: 1,
    resultItemId: 'light_leather',
    resultQuantity: 1,
    materials: [{ itemId: 'leather_scraps', quantity: 5 }],
    craftSeconds: 5,
    xpAward: 4,
    colorBreakpoints: { orangeUntil: 4, yellowUntil: 8, greenUntil: 16 },
  },
  leather_boots: {
    id: 'leather_boots',
    name: 'Leather Boots',
    profession: 'leatherworking',
    requiredSkill: 1,
    resultItemId: 'leather_boots',
    resultQuantity: 1,
    materials: [{ itemId: 'light_leather', quantity: 4 }],
    craftSeconds: 8,
    xpAward: 12,
    colorBreakpoints: { orangeUntil: 9, yellowUntil: 14, greenUntil: 24 },
  },
  leather_gloves: {
    id: 'leather_gloves',
    name: 'Leather Gloves',
    profession: 'leatherworking',
    requiredSkill: 5,
    resultItemId: 'leather_gloves',
    resultQuantity: 1,
    materials: [
      { itemId: 'light_leather', quantity: 5 },
      { itemId: 'linen_cloth', quantity: 2 },
    ],
    craftSeconds: 10,
    xpAward: 16,
    colorBreakpoints: { orangeUntil: 14, yellowUntil: 19, greenUntil: 29 },
  },
  leather_cap: {
    id: 'leather_cap',
    name: 'Leather Cap',
    profession: 'leatherworking',
    requiredSkill: 10,
    resultItemId: 'leather_cap',
    resultQuantity: 1,
    materials: [
      { itemId: 'light_leather', quantity: 6 },
      { itemId: 'linen_cloth', quantity: 3 },
    ],
    craftSeconds: 14,
    xpAward: 22,
    colorBreakpoints: { orangeUntil: 19, yellowUntil: 24, greenUntil: 34 },
  },

  copper_bar: {
    id: 'copper_bar',
    name: 'Copper Bar',
    profession: 'smithing',
    requiredSkill: 1,
    resultItemId: 'copper_bar',
    resultQuantity: 1,
    materials: [{ itemId: 'copper_ore', quantity: 2 }],
    craftSeconds: 4,
    xpAward: 5,
    colorBreakpoints: { orangeUntil: 5, yellowUntil: 10, greenUntil: 20 },
  },
  copper_chestguard: {
    id: 'copper_chestguard',
    name: 'Copper Chestguard',
    profession: 'smithing',
    requiredSkill: 3,
    resultItemId: 'copper_chestguard',
    resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 4 }],
    craftSeconds: 10,
    xpAward: 14,
    colorBreakpoints: { orangeUntil: 12, yellowUntil: 17, greenUntil: 27 },
  },
  copper_legguards: {
    id: 'copper_legguards',
    name: 'Copper Legguards',
    profession: 'smithing',
    requiredSkill: 7,
    resultItemId: 'copper_legguards',
    resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 5 }],
    craftSeconds: 12,
    xpAward: 18,
    colorBreakpoints: { orangeUntil: 16, yellowUntil: 21, greenUntil: 31 },
  },
  bronze_bar: {
    id: 'bronze_bar',
    name: 'Bronze Bar',
    profession: 'smithing',
    requiredSkill: 10,
    resultItemId: 'bronze_bar',
    resultQuantity: 1,
    materials: [
      { itemId: 'copper_bar', quantity: 1 },
      { itemId: 'tin_ore', quantity: 1 },
    ],
    craftSeconds: 6,
    xpAward: 10,
    colorBreakpoints: { orangeUntil: 15, yellowUntil: 20, greenUntil: 30 },
  },
  bronze_sword: {
    id: 'bronze_sword',
    name: 'Bronze Sword',
    profession: 'smithing',
    requiredSkill: 12,
    resultItemId: 'bronze_sword',
    resultQuantity: 1,
    materials: [{ itemId: 'bronze_bar', quantity: 4 }],
    craftSeconds: 16,
    xpAward: 26,
    colorBreakpoints: { orangeUntil: 21, yellowUntil: 26, greenUntil: 36 },
  },

  linen_robe: {
    id: 'linen_robe',
    name: 'Linen Robe',
    profession: 'tailoring',
    requiredSkill: 1,
    resultItemId: 'linen_robe',
    resultQuantity: 1,
    materials: [
      { itemId: 'linen_cloth', quantity: 5 },
      { itemId: 'simple_thread', quantity: 2 },
    ],
    craftSeconds: 9,
    xpAward: 13,
    colorBreakpoints: { orangeUntil: 9, yellowUntil: 14, greenUntil: 24 },
  },
  linen_gloves: {
    id: 'linen_gloves',
    name: 'Linen Gloves',
    profession: 'tailoring',
    requiredSkill: 5,
    resultItemId: 'linen_gloves',
    resultQuantity: 1,
    materials: [
      { itemId: 'linen_cloth', quantity: 4 },
      { itemId: 'simple_thread', quantity: 1 },
    ],
    craftSeconds: 8,
    xpAward: 14,
    colorBreakpoints: { orangeUntil: 14, yellowUntil: 19, greenUntil: 29 },
  },
  linen_cap: {
    id: 'linen_cap',
    name: 'Linen Cap',
    profession: 'tailoring',
    requiredSkill: 8,
    resultItemId: 'linen_cap',
    resultQuantity: 1,
    materials: [
      { itemId: 'linen_cloth', quantity: 5 },
      { itemId: 'simple_thread', quantity: 2 },
    ],
    craftSeconds: 10,
    xpAward: 17,
    colorBreakpoints: { orangeUntil: 17, yellowUntil: 22, greenUntil: 32 },
  },
  sage_leggings: {
    id: 'sage_leggings',
    name: 'Sage-Woven Leggings',
    profession: 'tailoring',
    requiredSkill: 12,
    resultItemId: 'sage_leggings',
    resultQuantity: 1,
    materials: [
      { itemId: 'coarse_cloth', quantity: 5 },
      { itemId: 'mountain_sage', quantity: 3 },
    ],
    craftSeconds: 13,
    xpAward: 22,
    colorBreakpoints: { orangeUntil: 21, yellowUntil: 26, greenUntil: 36 },
  },

  // ── Stonecrag Foothills leatherworking ───────────────────────────────
  coarse_leather: {
    id: 'coarse_leather',
    name: 'Coarse Leather',
    profession: 'leatherworking',
    requiredSkill: 12,
    resultItemId: 'coarse_leather',
    resultQuantity: 1,
    materials: [{ itemId: 'coarse_hide', quantity: 5 }],
    craftSeconds: 6,
    xpAward: 9,
    colorBreakpoints: { orangeUntil: 21, yellowUntil: 26, greenUntil: 36 },
  },
  reinforced_leather_vest: {
    id: 'reinforced_leather_vest',
    name: 'Reinforced Leather Vest',
    profession: 'leatherworking',
    requiredSkill: 15,
    resultItemId: 'reinforced_leather_vest',
    resultQuantity: 1,
    materials: [
      { itemId: 'coarse_leather', quantity: 5 },
      { itemId: 'thick_hide', quantity: 2 },
    ],
    craftSeconds: 16,
    xpAward: 24,
    colorBreakpoints: { orangeUntil: 24, yellowUntil: 29, greenUntil: 39 },
  },
  alphahide_gloves: {
    id: 'alphahide_gloves',
    name: 'Alphahide Gloves',
    profession: 'leatherworking',
    requiredSkill: 20,
    resultItemId: 'alphahide_gloves',
    resultQuantity: 1,
    materials: [
      { itemId: 'coarse_leather', quantity: 3 },
      { itemId: 'alpha_pelt', quantity: 1 },
    ],
    craftSeconds: 18,
    xpAward: 30,
    colorBreakpoints: { orangeUntil: 29, yellowUntil: 34, greenUntil: 44 },
  },

  // ── Alchemy ───────────────────────────────────────────────────────────
  minor_healing_draught: {
    id: 'minor_healing_draught',
    name: 'Minor Healing Draught',
    profession: 'alchemy',
    requiredSkill: 1,
    resultItemId: 'minor_healing_draught',
    resultQuantity: 1,
    materials: [{ itemId: 'peacebloom', quantity: 3 }],
    craftSeconds: 6,
    xpAward: 6,
    colorBreakpoints: { orangeUntil: 10, yellowUntil: 15, greenUntil: 25 },
  },
  minor_mana_draught: {
    id: 'minor_mana_draught',
    name: 'Minor Mana Draught',
    profession: 'alchemy',
    requiredSkill: 5,
    resultItemId: 'minor_mana_draught',
    resultQuantity: 1,
    materials: [{ itemId: 'peacebloom', quantity: 4 }],
    craftSeconds: 7,
    xpAward: 9,
    colorBreakpoints: { orangeUntil: 14, yellowUntil: 19, greenUntil: 29 },
  },
  sage_healing_potion: {
    id: 'sage_healing_potion',
    name: 'Sage Healing Potion',
    profession: 'alchemy',
    requiredSkill: 12,
    resultItemId: 'sage_healing_potion',
    resultQuantity: 1,
    materials: [{ itemId: 'mountain_sage', quantity: 3 }],
    craftSeconds: 10,
    xpAward: 16,
    colorBreakpoints: { orangeUntil: 21, yellowUntil: 26, greenUntil: 36 },
  },
};
