import type { Recipe } from './types';

export const RECIPES: Record<string, Recipe> = {
  light_leather: {
    id: 'light_leather',
    name: 'Light Leather',
    profession: 'leatherworking',
    requiredSkill: 1,
    resultItemId: 'light_leather',
    resultQuantity: 1,
    materials: [{ itemId: 'leather_scraps', quantity: 5 }],
    craftSeconds: 5,
    xpAward: 4,
    colorBreakpoints: { orangeUntil: 4, yellowUntil: 8, greenUntil: 16 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  leather_boots: {
    id: 'leather_boots',
    name: 'Leather Boots',
    profession: 'leatherworking',
    requiredSkill: 1,
    resultItemId: 'leather_boots',
    resultQuantity: 1,
    materials: [
      { itemId: 'light_leather', quantity: 4 },
      { itemId: 'rabbit_pelt', quantity: 2 },
    ],
    craftSeconds: 8,
    xpAward: 12,
    colorBreakpoints: { orangeUntil: 9, yellowUntil: 14, greenUntil: 24 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  leather_gloves: {
    id: 'leather_gloves',
    name: 'Leather Gloves',
    profession: 'leatherworking',
    requiredSkill: 5,
    resultItemId: 'leather_gloves',
    resultQuantity: 1,
    materials: [
      { itemId: 'light_leather', quantity: 5 },
      { itemId: 'linen_cloth', quantity: 2 },
    ],
    craftSeconds: 10,
    xpAward: 16,
    colorBreakpoints: { orangeUntil: 14, yellowUntil: 19, greenUntil: 29 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  leather_cap: {
    id: 'leather_cap',
    name: 'Leather Cap',
    profession: 'leatherworking',
    requiredSkill: 10,
    resultItemId: 'leather_cap',
    resultQuantity: 1,
    materials: [
      { itemId: 'light_leather', quantity: 6 },
      { itemId: 'linen_cloth', quantity: 3 },
      { itemId: 'jackal_fur', quantity: 2 },
    ],
    craftSeconds: 14,
    xpAward: 22,
    colorBreakpoints: { orangeUntil: 19, yellowUntil: 24, greenUntil: 34 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  copper_bar: {
    id: 'copper_bar',
    name: 'Copper Bar',
    profession: 'mining',
    requiredSkill: 1,
    resultItemId: 'copper_bar',
    resultQuantity: 1,
    materials: [{ itemId: 'copper_ore', quantity: 2 }],
    craftSeconds: 4,
    xpAward: 5,
    colorBreakpoints: { orangeUntil: 5, yellowUntil: 10, greenUntil: 20 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  copper_chestguard: {
    id: 'copper_chestguard',
    name: 'Copper Chestguard',
    profession: 'smithing',
    requiredSkill: 3,
    resultItemId: 'copper_chestguard',
    resultQuantity: 1,
    materials: [
      { itemId: 'copper_bar', quantity: 4 },
      { itemId: 'granite_chunk', quantity: 2 },
    ],
    craftSeconds: 10,
    xpAward: 14,
    colorBreakpoints: { orangeUntil: 12, yellowUntil: 17, greenUntil: 27 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  copper_legguards: {
    id: 'copper_legguards',
    name: 'Copper Legguards',
    profession: 'smithing',
    requiredSkill: 7,
    resultItemId: 'copper_legguards',
    resultQuantity: 1,
    materials: [{ itemId: 'copper_bar', quantity: 5 }],
    craftSeconds: 12,
    xpAward: 18,
    colorBreakpoints: { orangeUntil: 16, yellowUntil: 21, greenUntil: 31 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  bronze_bar: {
    id: 'bronze_bar',
    name: 'Bronze Bar',
    profession: 'mining',
    requiredSkill: 10,
    resultItemId: 'bronze_bar',
    resultQuantity: 1,
    materials: [
      { itemId: 'copper_bar', quantity: 1 },
      { itemId: 'tin_ore', quantity: 1 },
    ],
    craftSeconds: 6,
    xpAward: 10,
    colorBreakpoints: { orangeUntil: 15, yellowUntil: 20, greenUntil: 30 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  bronze_sword: {
    id: 'bronze_sword',
    name: 'Bronze Sword',
    profession: 'smithing',
    requiredSkill: 12,
    resultItemId: 'bronze_sword',
    resultQuantity: 1,
    materials: [
      { itemId: 'bronze_bar', quantity: 4 },
      { itemId: 'flint', quantity: 2 },
    ],
    craftSeconds: 16,
    xpAward: 26,
    colorBreakpoints: { orangeUntil: 21, yellowUntil: 26, greenUntil: 36 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  linen_robe: {
    id: 'linen_robe',
    name: 'Linen Robe',
    profession: 'tailoring',
    requiredSkill: 1,
    resultItemId: 'linen_robe',
    resultQuantity: 1,
    materials: [
      { itemId: 'linen_cloth', quantity: 5 },
      { itemId: 'simple_thread', quantity: 2 },
    ],
    craftSeconds: 9,
    xpAward: 13,
    colorBreakpoints: { orangeUntil: 9, yellowUntil: 14, greenUntil: 24 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  linen_gloves: {
    id: 'linen_gloves',
    name: 'Linen Gloves',
    profession: 'tailoring',
    requiredSkill: 5,
    resultItemId: 'linen_gloves',
    resultQuantity: 1,
    materials: [
      { itemId: 'linen_cloth', quantity: 4 },
      { itemId: 'simple_thread', quantity: 1 },
    ],
    craftSeconds: 8,
    xpAward: 14,
    colorBreakpoints: { orangeUntil: 14, yellowUntil: 19, greenUntil: 29 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  linen_cap: {
    id: 'linen_cap',
    name: 'Linen Cap',
    profession: 'tailoring',
    requiredSkill: 8,
    resultItemId: 'linen_cap',
    resultQuantity: 1,
    materials: [
      { itemId: 'linen_cloth', quantity: 5 },
      { itemId: 'simple_thread', quantity: 2 },
    ],
    craftSeconds: 10,
    xpAward: 17,
    colorBreakpoints: { orangeUntil: 17, yellowUntil: 22, greenUntil: 32 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  linen_boots: {
    id: 'linen_boots',
    name: 'Linen Boots',
    profession: 'tailoring',
    requiredSkill: 7,
    resultItemId: 'linen_boots',
    resultQuantity: 1,
    materials: [
      { itemId: 'linen_cloth', quantity: 4 },
      { itemId: 'simple_thread', quantity: 1 },
    ],
    craftSeconds: 9,
    xpAward: 16,
    colorBreakpoints: { orangeUntil: 16, yellowUntil: 21, greenUntil: 31 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  sage_leggings: {
    id: 'sage_leggings',
    name: 'Sage-Woven Leggings',
    profession: 'tailoring',
    requiredSkill: 12,
    resultItemId: 'sage_leggings',
    resultQuantity: 1,
    materials: [
      { itemId: 'coarse_cloth', quantity: 5 },
      { itemId: 'mountain_sage', quantity: 3 },
    ],
    craftSeconds: 13,
    xpAward: 22,
    colorBreakpoints: { orangeUntil: 21, yellowUntil: 26, greenUntil: 36 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Stonecrag Foothills leatherworking ───────────────────────────────
  coarse_leather: {
    id: 'coarse_leather',
    name: 'Coarse Leather',
    profession: 'leatherworking',
    requiredSkill: 12,
    resultItemId: 'coarse_leather',
    resultQuantity: 1,
    materials: [{ itemId: 'coarse_hide', quantity: 5 }],
    craftSeconds: 6,
    xpAward: 9,
    colorBreakpoints: { orangeUntil: 21, yellowUntil: 26, greenUntil: 36 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  reinforced_leather_vest: {
    id: 'reinforced_leather_vest',
    name: 'Reinforced Leather Vest',
    profession: 'leatherworking',
    requiredSkill: 15,
    resultItemId: 'reinforced_leather_vest',
    resultQuantity: 1,
    materials: [
      { itemId: 'coarse_leather', quantity: 5 },
      { itemId: 'thick_hide', quantity: 2 },
    ],
    craftSeconds: 16,
    xpAward: 24,
    colorBreakpoints: { orangeUntil: 24, yellowUntil: 29, greenUntil: 39 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  alphahide_gloves: {
    id: 'alphahide_gloves',
    name: 'Alphahide Gloves',
    profession: 'leatherworking',
    requiredSkill: 20,
    resultItemId: 'alphahide_gloves',
    resultQuantity: 1,
    materials: [
      { itemId: 'coarse_leather', quantity: 3 },
      { itemId: 'alpha_pelt', quantity: 1 },
    ],
    craftSeconds: 18,
    xpAward: 30,
    colorBreakpoints: { orangeUntil: 29, yellowUntil: 34, greenUntil: 44 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  thick_hide_cap: {
    id: 'thick_hide_cap',
    name: 'Thick Hide Cap',
    profession: 'leatherworking',
    requiredSkill: 18,
    resultItemId: 'thick_hide_cap',
    resultQuantity: 1,
    materials: [{ itemId: 'coarse_leather', quantity: 4 }],
    craftSeconds: 15,
    xpAward: 27,
    colorBreakpoints: { orangeUntil: 27, yellowUntil: 32, greenUntil: 42 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ridgehide_boots: {
    id: 'ridgehide_boots',
    name: 'Ridgehide Boots',
    profession: 'leatherworking',
    requiredSkill: 22,
    resultItemId: 'ridgehide_boots',
    resultQuantity: 1,
    materials: [
      { itemId: 'coarse_leather', quantity: 3 },
      { itemId: 'thick_hide', quantity: 1 },
    ],
    craftSeconds: 17,
    xpAward: 29,
    colorBreakpoints: { orangeUntil: 31, yellowUntil: 36, greenUntil: 46 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Alchemy ───────────────────────────────────────────────────────────
  minor_healing_draught: {
    id: 'minor_healing_draught',
    name: 'Minor Healing Draught',
    profession: 'alchemy',
    requiredSkill: 1,
    resultItemId: 'minor_healing_draught',
    resultQuantity: 1,
    materials: [
      { itemId: 'peacebloom', quantity: 3 },
      { itemId: 'wildroot', quantity: 1 },
    ],
    craftSeconds: 6,
    xpAward: 6,
    colorBreakpoints: { orangeUntil: 10, yellowUntil: 15, greenUntil: 25 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  minor_mana_draught: {
    id: 'minor_mana_draught',
    name: 'Minor Mana Draught',
    profession: 'alchemy',
    requiredSkill: 5,
    resultItemId: 'minor_mana_draught',
    resultQuantity: 1,
    materials: [{ itemId: 'peacebloom', quantity: 4 }],
    craftSeconds: 7,
    xpAward: 9,
    colorBreakpoints: { orangeUntil: 14, yellowUntil: 19, greenUntil: 29 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  sage_healing_potion: {
    id: 'sage_healing_potion',
    name: 'Sage Healing Potion',
    profession: 'alchemy',
    requiredSkill: 12,
    resultItemId: 'sage_healing_potion',
    resultQuantity: 1,
    materials: [
      { itemId: 'mountain_sage', quantity: 3 },
      { itemId: 'frostcap', quantity: 1 },
    ],
    craftSeconds: 10,
    xpAward: 16,
    colorBreakpoints: { orangeUntil: 21, yellowUntil: 26, greenUntil: 36 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  sunpetal_elixir: {
    id: 'sunpetal_elixir',
    name: 'Sunpetal Elixir',
    profession: 'alchemy',
    requiredSkill: 25,
    resultItemId: 'sunpetal_elixir',
    resultQuantity: 1,
    materials: [
      { itemId: 'sunpetal', quantity: 4 },
      { itemId: 'emberleaf', quantity: 2 },
    ],
    craftSeconds: 12,
    xpAward: 22,
    colorBreakpoints: { orangeUntil: 34, yellowUntil: 39, greenUntil: 49 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Emberfall Ridge smithing ──────────────────────────────────────────
  iron_bar: {
    id: 'iron_bar',
    name: 'Iron Bar',
    profession: 'mining',
    requiredSkill: 25,
    resultItemId: 'iron_bar',
    resultQuantity: 1,
    materials: [{ itemId: 'iron_ore', quantity: 2 }],
    craftSeconds: 8,
    xpAward: 16,
    colorBreakpoints: { orangeUntil: 30, yellowUntil: 35, greenUntil: 45 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  iron_chestguard: {
    id: 'iron_chestguard',
    name: 'Iron Chestguard',
    profession: 'smithing',
    requiredSkill: 28,
    resultItemId: 'iron_chestguard',
    resultQuantity: 1,
    materials: [
      { itemId: 'iron_bar', quantity: 5 },
      { itemId: 'sulfur_chunk', quantity: 2 },
    ],
    craftSeconds: 14,
    xpAward: 24,
    colorBreakpoints: { orangeUntil: 37, yellowUntil: 42, greenUntil: 52 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  iron_greatsword: {
    id: 'iron_greatsword',
    name: 'Iron Greatsword',
    profession: 'smithing',
    requiredSkill: 33,
    resultItemId: 'iron_greatsword',
    resultQuantity: 1,
    materials: [{ itemId: 'iron_bar', quantity: 6 }],
    craftSeconds: 18,
    xpAward: 32,
    colorBreakpoints: { orangeUntil: 42, yellowUntil: 47, greenUntil: 57 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Emberfall Ridge leatherworking ────────────────────────────────────
  scaled_leather: {
    id: 'scaled_leather',
    name: 'Scaled Leather',
    profession: 'leatherworking',
    requiredSkill: 25,
    resultItemId: 'scaled_leather',
    resultQuantity: 1,
    materials: [{ itemId: 'scaled_hide', quantity: 5 }],
    craftSeconds: 7,
    xpAward: 13,
    colorBreakpoints: { orangeUntil: 34, yellowUntil: 39, greenUntil: 49 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaled_leggings: {
    id: 'scaled_leggings',
    name: 'Scaled Leggings',
    profession: 'leatherworking',
    requiredSkill: 28,
    resultItemId: 'scaled_leggings',
    resultQuantity: 1,
    materials: [{ itemId: 'scaled_leather', quantity: 5 }],
    craftSeconds: 15,
    xpAward: 26,
    colorBreakpoints: { orangeUntil: 37, yellowUntil: 42, greenUntil: 52 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  drakescale_boots: {
    id: 'drakescale_boots',
    name: 'Drakescale Boots',
    profession: 'leatherworking',
    requiredSkill: 33,
    resultItemId: 'drakescale_boots',
    resultQuantity: 1,
    materials: [
      { itemId: 'scaled_leather', quantity: 4 },
      { itemId: 'ember_shard', quantity: 1 },
    ],
    craftSeconds: 16,
    xpAward: 32,
    colorBreakpoints: { orangeUntil: 42, yellowUntil: 47, greenUntil: 57 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaled_gloves: {
    id: 'scaled_gloves', name: 'Scaled Gloves', profession: 'leatherworking', requiredSkill: 26,
    resultItemId: 'scaled_gloves', resultQuantity: 1,
    materials: [
      { itemId: 'scaled_leather', quantity: 3 },
      { itemId: 'cinderwolf_pelt', quantity: 2 },
    ],
    craftSeconds: 14, xpAward: 24,
    colorBreakpoints: { orangeUntil: 35, yellowUntil: 40, greenUntil: 50 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaled_cap: {
    id: 'scaled_cap', name: 'Scaled Cap', profession: 'leatherworking', requiredSkill: 30,
    resultItemId: 'scaled_cap', resultQuantity: 1,
    materials: [{ itemId: 'scaled_leather', quantity: 4 }],
    craftSeconds: 15, xpAward: 28,
    colorBreakpoints: { orangeUntil: 39, yellowUntil: 44, greenUntil: 54 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Emberfall Ridge tailoring ─────────────────────────────────────────
  heavy_robe: {
    id: 'heavy_robe',
    name: 'Heavy Robe',
    profession: 'tailoring',
    requiredSkill: 26,
    resultItemId: 'heavy_robe',
    resultQuantity: 1,
    materials: [
      { itemId: 'heavy_cloth', quantity: 5 },
      { itemId: 'simple_thread', quantity: 2 },
    ],
    craftSeconds: 12,
    xpAward: 22,
    colorBreakpoints: { orangeUntil: 35, yellowUntil: 40, greenUntil: 50 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  heavy_leggings: {
    id: 'heavy_leggings', name: 'Heavy Leggings', profession: 'tailoring', requiredSkill: 29,
    resultItemId: 'heavy_leggings', resultQuantity: 1,
    materials: [{ itemId: 'heavy_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 13, xpAward: 24,
    colorBreakpoints: { orangeUntil: 38, yellowUntil: 43, greenUntil: 53 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  heavy_gloves: {
    id: 'heavy_gloves', name: 'Heavy Gloves', profession: 'tailoring', requiredSkill: 27,
    resultItemId: 'heavy_gloves', resultQuantity: 1,
    materials: [{ itemId: 'heavy_cloth', quantity: 3 }],
    craftSeconds: 11, xpAward: 20,
    colorBreakpoints: { orangeUntil: 36, yellowUntil: 41, greenUntil: 51 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  heavy_cap: {
    id: 'heavy_cap', name: 'Heavy Cap', profession: 'tailoring', requiredSkill: 31,
    resultItemId: 'heavy_cap', resultQuantity: 1,
    materials: [{ itemId: 'heavy_cloth', quantity: 4 }],
    craftSeconds: 12, xpAward: 22,
    colorBreakpoints: { orangeUntil: 40, yellowUntil: 45, greenUntil: 55 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  heavy_boots: {
    id: 'heavy_boots', name: 'Heavy Boots', profession: 'tailoring', requiredSkill: 28,
    resultItemId: 'heavy_boots', resultQuantity: 1,
    materials: [{ itemId: 'heavy_cloth', quantity: 4 }],
    craftSeconds: 12, xpAward: 21,
    colorBreakpoints: { orangeUntil: 37, yellowUntil: 42, greenUntil: 52 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Cinderfall Depths ──────────────────────────────────────────────────
  cinder_steel_bar: {
    id: 'cinder_steel_bar', name: 'Cinder Steel Bar', profession: 'mining', requiredSkill: 30,
    resultItemId: 'cinder_steel_bar', resultQuantity: 1,
    materials: [{ itemId: 'cinderore', quantity: 2 }],
    craftSeconds: 9, xpAward: 18,
    colorBreakpoints: { orangeUntil: 35, yellowUntil: 40, greenUntil: 50 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  cinderplate_chestguard: {
    id: 'cinderplate_chestguard', name: 'Cinderplate Chestguard', profession: 'smithing', requiredSkill: 33,
    resultItemId: 'cinderplate_chestguard', resultQuantity: 1,
    materials: [
      { itemId: 'cinder_steel_bar', quantity: 5 },
      { itemId: 'shadowore', quantity: 2 },
    ],
    craftSeconds: 15, xpAward: 26,
    colorBreakpoints: { orangeUntil: 42, yellowUntil: 47, greenUntil: 57 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  cinderforged_hammer: {
    id: 'cinderforged_hammer', name: 'Cinderforged Hammer', profession: 'smithing', requiredSkill: 38,
    resultItemId: 'cinderforged_hammer', resultQuantity: 1,
    materials: [{ itemId: 'cinder_steel_bar', quantity: 6 }],
    craftSeconds: 19, xpAward: 34,
    colorBreakpoints: { orangeUntil: 47, yellowUntil: 52, greenUntil: 62 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashhide_leather: {
    id: 'ashhide_leather', name: 'Ashhide Leather', profession: 'leatherworking', requiredSkill: 30,
    resultItemId: 'ashhide_leather', resultQuantity: 1,
    materials: [
      { itemId: 'ashhide', quantity: 5 },
      { itemId: 'scavenger_hide', quantity: 2 },
    ],
    craftSeconds: 8, xpAward: 15,
    colorBreakpoints: { orangeUntil: 39, yellowUntil: 44, greenUntil: 54 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashhide_leggings: {
    id: 'ashhide_leggings', name: 'Ashhide Leggings', profession: 'leatherworking', requiredSkill: 33,
    resultItemId: 'ashhide_leggings', resultQuantity: 1,
    materials: [{ itemId: 'ashhide_leather', quantity: 5 }],
    craftSeconds: 16, xpAward: 28,
    colorBreakpoints: { orangeUntil: 42, yellowUntil: 47, greenUntil: 57 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashhide_boots: {
    id: 'ashhide_boots', name: 'Ashhide Boots', profession: 'leatherworking', requiredSkill: 38,
    resultItemId: 'ashhide_boots', resultQuantity: 1,
    materials: [{ itemId: 'ashhide_leather', quantity: 4 }, { itemId: 'cindercore_shard', quantity: 1 }],
    craftSeconds: 17, xpAward: 34,
    colorBreakpoints: { orangeUntil: 47, yellowUntil: 52, greenUntil: 62 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashhide_gloves: {
    id: 'ashhide_gloves', name: 'Ashhide Gloves', profession: 'leatherworking', requiredSkill: 31,
    resultItemId: 'ashhide_gloves', resultQuantity: 1,
    materials: [{ itemId: 'ashhide_leather', quantity: 3 }],
    craftSeconds: 15, xpAward: 26,
    colorBreakpoints: { orangeUntil: 40, yellowUntil: 45, greenUntil: 55 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashhide_cap: {
    id: 'ashhide_cap', name: 'Ashhide Cap', profession: 'leatherworking', requiredSkill: 35,
    resultItemId: 'ashhide_cap', resultQuantity: 1,
    materials: [{ itemId: 'ashhide_leather', quantity: 4 }],
    craftSeconds: 16, xpAward: 30,
    colorBreakpoints: { orangeUntil: 44, yellowUntil: 49, greenUntil: 59 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashwoven_robe: {
    id: 'ashwoven_robe', name: 'Ashwoven Robe', profession: 'tailoring', requiredSkill: 31,
    resultItemId: 'ashwoven_robe', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 13, xpAward: 24,
    colorBreakpoints: { orangeUntil: 40, yellowUntil: 45, greenUntil: 55 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashwoven_leggings: {
    id: 'ashwoven_leggings', name: 'Ashwoven Leggings', profession: 'tailoring', requiredSkill: 32,
    resultItemId: 'ashwoven_leggings', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 14, xpAward: 26,
    colorBreakpoints: { orangeUntil: 41, yellowUntil: 46, greenUntil: 56 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashwoven_gloves: {
    id: 'ashwoven_gloves', name: 'Ashwoven Gloves', profession: 'tailoring', requiredSkill: 30,
    resultItemId: 'ashwoven_gloves', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 3 }],
    craftSeconds: 12, xpAward: 22,
    colorBreakpoints: { orangeUntil: 39, yellowUntil: 44, greenUntil: 54 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashwoven_cap: {
    id: 'ashwoven_cap', name: 'Ashwoven Cap', profession: 'tailoring', requiredSkill: 34,
    resultItemId: 'ashwoven_cap', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 4 }],
    craftSeconds: 13, xpAward: 24,
    colorBreakpoints: { orangeUntil: 43, yellowUntil: 48, greenUntil: 58 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashwoven_boots: {
    id: 'ashwoven_boots', name: 'Ashwoven Boots', profession: 'tailoring', requiredSkill: 33,
    resultItemId: 'ashwoven_boots', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 4 }],
    craftSeconds: 13, xpAward: 23,
    colorBreakpoints: { orangeUntil: 42, yellowUntil: 47, greenUntil: 57 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberpetal_tonic: {
    id: 'emberpetal_tonic', name: 'Emberpetal Tonic', profession: 'alchemy', requiredSkill: 30,
    resultItemId: 'emberpetal_tonic', resultQuantity: 1,
    materials: [
      { itemId: 'emberpetal', quantity: 4 },
      { itemId: 'ashroot', quantity: 2 },
    ],
    craftSeconds: 13, xpAward: 24,
    colorBreakpoints: { orangeUntil: 39, yellowUntil: 44, greenUntil: 54 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── The Molten Scar ────────────────────────────────────────────────────
  brimstone_bar: {
    id: 'brimstone_bar', name: 'Brimstone Bar', profession: 'mining', requiredSkill: 40,
    resultItemId: 'brimstone_bar', resultQuantity: 1,
    materials: [{ itemId: 'brimstone_ore', quantity: 2 }],
    craftSeconds: 10, xpAward: 20,
    colorBreakpoints: { orangeUntil: 45, yellowUntil: 50, greenUntil: 60 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  brimstone_plate: {
    id: 'brimstone_plate', name: 'Brimstone Plate', profession: 'smithing', requiredSkill: 43,
    resultItemId: 'brimstone_plate', resultQuantity: 1,
    materials: [
      { itemId: 'brimstone_bar', quantity: 5 },
      { itemId: 'obsidian_shard', quantity: 1 },
    ],
    craftSeconds: 16, xpAward: 28,
    colorBreakpoints: { orangeUntil: 52, yellowUntil: 57, greenUntil: 67 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  brimstone_greatsword: {
    id: 'brimstone_greatsword', name: 'Brimstone Greatsword', profession: 'smithing', requiredSkill: 48,
    resultItemId: 'brimstone_greatsword', resultQuantity: 1,
    materials: [{ itemId: 'brimstone_bar', quantity: 6 }],
    craftSeconds: 20, xpAward: 36,
    colorBreakpoints: { orangeUntil: 57, yellowUntil: 62, greenUntil: 72 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaleback_leather: {
    id: 'scaleback_leather', name: 'Scaleback Leather', profession: 'leatherworking', requiredSkill: 40,
    resultItemId: 'scaleback_leather', resultQuantity: 1,
    materials: [
      { itemId: 'scaleback_hide', quantity: 5 },
      { itemId: 'scaleback_scale', quantity: 2 },
    ],
    craftSeconds: 9, xpAward: 17,
    colorBreakpoints: { orangeUntil: 49, yellowUntil: 54, greenUntil: 64 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaleback_leggings: {
    id: 'scaleback_leggings', name: 'Scaleback Leggings', profession: 'leatherworking', requiredSkill: 43,
    resultItemId: 'scaleback_leggings', resultQuantity: 1,
    materials: [{ itemId: 'scaleback_leather', quantity: 5 }],
    craftSeconds: 17, xpAward: 30,
    colorBreakpoints: { orangeUntil: 52, yellowUntil: 57, greenUntil: 67 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaleback_boots: {
    id: 'scaleback_boots', name: 'Scaleback Boots', profession: 'leatherworking', requiredSkill: 48,
    resultItemId: 'scaleback_boots', resultQuantity: 1,
    materials: [{ itemId: 'scaleback_leather', quantity: 4 }, { itemId: 'magma_heart', quantity: 1 }],
    craftSeconds: 18, xpAward: 36,
    colorBreakpoints: { orangeUntil: 57, yellowUntil: 62, greenUntil: 72 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaleback_gloves: {
    id: 'scaleback_gloves', name: 'Scaleback Gloves', profession: 'leatherworking', requiredSkill: 41,
    resultItemId: 'scaleback_gloves', resultQuantity: 1,
    materials: [{ itemId: 'scaleback_leather', quantity: 3 }],
    craftSeconds: 16, xpAward: 28,
    colorBreakpoints: { orangeUntil: 50, yellowUntil: 55, greenUntil: 65 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  scaleback_cap: {
    id: 'scaleback_cap', name: 'Scaleback Cap', profession: 'leatherworking', requiredSkill: 45,
    resultItemId: 'scaleback_cap', resultQuantity: 1,
    materials: [{ itemId: 'scaleback_leather', quantity: 4 }],
    craftSeconds: 17, xpAward: 32,
    colorBreakpoints: { orangeUntil: 54, yellowUntil: 59, greenUntil: 69 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  charred_robe: {
    id: 'charred_robe', name: 'Charred Robe', profession: 'tailoring', requiredSkill: 41,
    resultItemId: 'charred_robe', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 14, xpAward: 26,
    colorBreakpoints: { orangeUntil: 50, yellowUntil: 55, greenUntil: 65 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  charred_leggings: {
    id: 'charred_leggings', name: 'Charred Leggings', profession: 'tailoring', requiredSkill: 42,
    resultItemId: 'charred_leggings', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 15, xpAward: 28,
    colorBreakpoints: { orangeUntil: 51, yellowUntil: 56, greenUntil: 66 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  charred_gloves: {
    id: 'charred_gloves', name: 'Charred Gloves', profession: 'tailoring', requiredSkill: 40,
    resultItemId: 'charred_gloves', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 3 }],
    craftSeconds: 13, xpAward: 24,
    colorBreakpoints: { orangeUntil: 49, yellowUntil: 54, greenUntil: 64 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  charred_boots: {
    id: 'charred_boots', name: 'Charred Boots', profession: 'tailoring', requiredSkill: 43,
    resultItemId: 'charred_boots', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 4 }],
    craftSeconds: 14, xpAward: 25,
    colorBreakpoints: { orangeUntil: 52, yellowUntil: 57, greenUntil: 67 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  charred_cap: {
    id: 'charred_cap', name: 'Charred Cap', profession: 'tailoring', requiredSkill: 44,
    resultItemId: 'charred_cap', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 4 }],
    craftSeconds: 14, xpAward: 26,
    colorBreakpoints: { orangeUntil: 53, yellowUntil: 58, greenUntil: 68 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  cinderbloom_elixir: {
    id: 'cinderbloom_elixir', name: 'Cinderbloom Elixir', profession: 'alchemy', requiredSkill: 40,
    resultItemId: 'cinderbloom_elixir', resultQuantity: 1,
    materials: [
      { itemId: 'cinderbloom', quantity: 4 },
      { itemId: 'scorchweed', quantity: 2 },
    ],
    craftSeconds: 14, xpAward: 26,
    colorBreakpoints: { orangeUntil: 49, yellowUntil: 54, greenUntil: 64 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Cinderheart Crater ─────────────────────────────────────────────────
  emberforged_bar: {
    id: 'emberforged_bar', name: 'Emberforged Bar', profession: 'mining', requiredSkill: 48,
    resultItemId: 'emberforged_bar', resultQuantity: 1,
    materials: [{ itemId: 'emberforge_ore', quantity: 2 }],
    craftSeconds: 11, xpAward: 22,
    colorBreakpoints: { orangeUntil: 53, yellowUntil: 58, greenUntil: 68 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberforged_chestguard: {
    id: 'emberforged_chestguard', name: 'Emberforged Chestguard', profession: 'smithing', requiredSkill: 51,
    resultItemId: 'emberforged_chestguard', resultQuantity: 1,
    materials: [
      { itemId: 'emberforged_bar', quantity: 5 },
      { itemId: 'starforge_ore', quantity: 2 },
    ],
    craftSeconds: 17, xpAward: 30,
    colorBreakpoints: { orangeUntil: 60, yellowUntil: 65, greenUntil: 75 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberforged_greatsword: {
    id: 'emberforged_greatsword', name: 'Emberforged Greatsword', profession: 'smithing', requiredSkill: 56,
    resultItemId: 'emberforged_greatsword', resultQuantity: 1,
    materials: [{ itemId: 'emberforged_bar', quantity: 6 }],
    craftSeconds: 21, xpAward: 38,
    colorBreakpoints: { orangeUntil: 65, yellowUntil: 70, greenUntil: 80 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberscale_leather: {
    id: 'emberscale_leather', name: 'Emberscale Leather', profession: 'leatherworking', requiredSkill: 48,
    resultItemId: 'emberscale_leather', resultQuantity: 1,
    materials: [
      { itemId: 'emberscale_hide', quantity: 5 },
      { itemId: 'emberscale_claw', quantity: 2 },
    ],
    craftSeconds: 10, xpAward: 19,
    colorBreakpoints: { orangeUntil: 57, yellowUntil: 62, greenUntil: 72 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberscale_leggings: {
    id: 'emberscale_leggings', name: 'Emberscale Leggings', profession: 'leatherworking', requiredSkill: 51,
    resultItemId: 'emberscale_leggings', resultQuantity: 1,
    materials: [{ itemId: 'emberscale_leather', quantity: 5 }],
    craftSeconds: 18, xpAward: 32,
    colorBreakpoints: { orangeUntil: 60, yellowUntil: 65, greenUntil: 75 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberscale_boots: {
    id: 'emberscale_boots', name: 'Emberscale Boots', profession: 'leatherworking', requiredSkill: 56,
    resultItemId: 'emberscale_boots', resultQuantity: 1,
    materials: [{ itemId: 'emberscale_leather', quantity: 4 }, { itemId: 'emberlords_ash', quantity: 1 }],
    craftSeconds: 19, xpAward: 38,
    colorBreakpoints: { orangeUntil: 65, yellowUntil: 70, greenUntil: 80 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberscale_gloves: {
    id: 'emberscale_gloves', name: 'Emberscale Gloves', profession: 'leatherworking', requiredSkill: 49,
    resultItemId: 'emberscale_gloves', resultQuantity: 1,
    materials: [{ itemId: 'emberscale_leather', quantity: 3 }],
    craftSeconds: 17, xpAward: 30,
    colorBreakpoints: { orangeUntil: 58, yellowUntil: 63, greenUntil: 73 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberscale_cap: {
    id: 'emberscale_cap', name: 'Emberscale Cap', profession: 'leatherworking', requiredSkill: 53,
    resultItemId: 'emberscale_cap', resultQuantity: 1,
    materials: [{ itemId: 'emberscale_leather', quantity: 4 }],
    craftSeconds: 18, xpAward: 34,
    colorBreakpoints: { orangeUntil: 62, yellowUntil: 67, greenUntil: 77 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashenweave_robe: {
    id: 'ashenweave_robe', name: 'Ashenweave Robe', profession: 'tailoring', requiredSkill: 49,
    resultItemId: 'ashenweave_robe', resultQuantity: 1,
    materials: [{ itemId: 'ashenweave_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 15, xpAward: 28,
    colorBreakpoints: { orangeUntil: 58, yellowUntil: 63, greenUntil: 73 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashenweave_leggings: {
    id: 'ashenweave_leggings', name: 'Ashenweave Leggings', profession: 'tailoring', requiredSkill: 50,
    resultItemId: 'ashenweave_leggings', resultQuantity: 1,
    materials: [{ itemId: 'ashenweave_cloth', quantity: 5 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 16, xpAward: 30,
    colorBreakpoints: { orangeUntil: 59, yellowUntil: 64, greenUntil: 74 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashenweave_gloves: {
    id: 'ashenweave_gloves', name: 'Ashenweave Gloves', profession: 'tailoring', requiredSkill: 48,
    resultItemId: 'ashenweave_gloves', resultQuantity: 1,
    materials: [{ itemId: 'ashenweave_cloth', quantity: 3 }],
    craftSeconds: 14, xpAward: 26,
    colorBreakpoints: { orangeUntil: 57, yellowUntil: 62, greenUntil: 72 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashenweave_cap: {
    id: 'ashenweave_cap', name: 'Ashenweave Cap', profession: 'tailoring', requiredSkill: 52,
    resultItemId: 'ashenweave_cap', resultQuantity: 1,
    materials: [{ itemId: 'ashenweave_cloth', quantity: 4 }],
    craftSeconds: 15, xpAward: 28,
    colorBreakpoints: { orangeUntil: 61, yellowUntil: 66, greenUntil: 76 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  ashenweave_boots: {
    id: 'ashenweave_boots', name: 'Ashenweave Boots', profession: 'tailoring', requiredSkill: 51,
    resultItemId: 'ashenweave_boots', resultQuantity: 1,
    materials: [{ itemId: 'ashenweave_cloth', quantity: 4 }],
    craftSeconds: 15, xpAward: 27,
    colorBreakpoints: { orangeUntil: 60, yellowUntil: 65, greenUntil: 75 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },
  emberheart_potion: {
    id: 'emberheart_potion', name: 'Emberheart Potion', profession: 'alchemy', requiredSkill: 48,
    resultItemId: 'emberheart_potion', resultQuantity: 1,
    materials: [
      { itemId: 'emberheart_bloom', quantity: 4 },
      { itemId: 'heartbloom', quantity: 2 },
    ],
    craftSeconds: 15, xpAward: 28,
    colorBreakpoints: { orangeUntil: 57, yellowUntil: 62, greenUntil: 72 },
    source: 'trainer',
    rarity: 'common',
    learnedAutomatically: true,
  },

  // ── Alchemy buff potions — spread across the full 1-300 skill range to
  // actually exercise Journeyman/Expert/Artisan, unlike the pre-overhaul
  // recipe set which topped out around skill 56.
  mana_potion: {
    id: 'mana_potion', name: 'Mana Potion', profession: 'alchemy', requiredSkill: 10,
    resultItemId: 'mana_potion', resultQuantity: 1,
    materials: [{ itemId: 'peacebloom', quantity: 4 }],
    craftSeconds: 10, xpAward: 8,
    colorBreakpoints: { orangeUntil: 19, yellowUntil: 24, greenUntil: 34 },
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  minor_battle_draught: {
    id: 'minor_battle_draught', name: 'Minor Battle Draught', profession: 'alchemy', requiredSkill: 50,
    resultItemId: 'minor_battle_draught', resultQuantity: 1,
    materials: [{ itemId: 'mountain_sage', quantity: 5 }],
    craftSeconds: 12, xpAward: 24,
    colorBreakpoints: { orangeUntil: 59, yellowUntil: 64, greenUntil: 74 },
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  minor_stoneskin_draught: {
    id: 'minor_stoneskin_draught', name: 'Minor Stoneskin Draught', profession: 'alchemy', requiredSkill: 65,
    resultItemId: 'minor_stoneskin_draught', resultQuantity: 1,
    materials: [{ itemId: 'mountain_sage', quantity: 6 }],
    craftSeconds: 12, xpAward: 28,
    colorBreakpoints: { orangeUntil: 74, yellowUntil: 79, greenUntil: 89 },
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  tonic_of_might: {
    id: 'tonic_of_might', name: 'Tonic of Might', profession: 'alchemy', requiredSkill: 90,
    resultItemId: 'tonic_of_might', resultQuantity: 1,
    materials: [{ itemId: 'sunpetal', quantity: 5 }],
    craftSeconds: 14, xpAward: 34,
    colorBreakpoints: { orangeUntil: 99, yellowUntil: 104, greenUntil: 114 },
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  elixir_of_the_mind: {
    id: 'elixir_of_the_mind', name: 'Elixir of the Mind', profession: 'alchemy', requiredSkill: 100,
    resultItemId: 'elixir_of_the_mind', resultQuantity: 1,
    materials: [{ itemId: 'sunpetal', quantity: 6 }],
    craftSeconds: 14, xpAward: 36,
    colorBreakpoints: { orangeUntil: 109, yellowUntil: 114, greenUntil: 124 },
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  draught_of_resistance: {
    id: 'draught_of_resistance', name: 'Draught of Resistance', profession: 'alchemy', requiredSkill: 130,
    resultItemId: 'draught_of_resistance', resultQuantity: 1,
    materials: [{ itemId: 'emberpetal', quantity: 6 }],
    craftSeconds: 16, xpAward: 44,
    colorBreakpoints: { orangeUntil: 139, yellowUntil: 144, greenUntil: 154 },
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  potion_of_precision: {
    id: 'potion_of_precision', name: 'Potion of Precision', profession: 'alchemy', requiredSkill: 160,
    resultItemId: 'potion_of_precision', resultQuantity: 1,
    materials: [{ itemId: 'cinderbloom', quantity: 6 }],
    craftSeconds: 16, xpAward: 50,
    colorBreakpoints: { orangeUntil: 169, yellowUntil: 174, greenUntil: 184 },
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  potion_of_evasion: {
    id: 'potion_of_evasion', name: 'Potion of Evasion', profession: 'alchemy', requiredSkill: 170,
    resultItemId: 'potion_of_evasion', resultQuantity: 1,
    materials: [{ itemId: 'cinderbloom', quantity: 7 }],
    craftSeconds: 16, xpAward: 52,
    colorBreakpoints: { orangeUntil: 179, yellowUntil: 184, greenUntil: 194 },
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  greater_battle_draught: {
    id: 'greater_battle_draught', name: 'Greater Battle Draught', profession: 'alchemy', requiredSkill: 220,
    resultItemId: 'greater_battle_draught', resultQuantity: 1,
    materials: [{ itemId: 'emberheart_bloom', quantity: 6 }],
    craftSeconds: 18, xpAward: 65,
    colorBreakpoints: { orangeUntil: 229, yellowUntil: 234, greenUntil: 244 },
    source: 'trainer', rarity: 'rare', learnedAutomatically: true,
  },
  greater_stoneskin_draught: {
    id: 'greater_stoneskin_draught', name: 'Greater Stoneskin Draught', profession: 'alchemy', requiredSkill: 260,
    resultItemId: 'greater_stoneskin_draught', resultQuantity: 1,
    materials: [{ itemId: 'emberheart_bloom', quantity: 8 }],
    craftSeconds: 18, xpAward: 75,
    colorBreakpoints: { orangeUntil: 269, yellowUntil: 274, greenUntil: 284 },
    source: 'trainer', rarity: 'rare', learnedAutomatically: true,
  },

  // ── Cooking — one dish per zone's fish, also spread across the full
  // skill range.
  farmhouse_stew: {
    id: 'farmhouse_stew', name: 'Farmhouse Stew', profession: 'cooking', requiredSkill: 5,
    resultItemId: 'farmhouse_stew', resultQuantity: 1,
    materials: [{ itemId: 'brook_trout', quantity: 3 }],
    craftSeconds: 8, xpAward: 6,
    colorBreakpoints: { orangeUntil: 14, yellowUntil: 19, greenUntil: 29 },
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  highland_roast: {
    id: 'highland_roast', name: 'Highland Roast', profession: 'cooking', requiredSkill: 50,
    resultItemId: 'highland_roast', resultQuantity: 1,
    materials: [{ itemId: 'mountain_char', quantity: 4 }],
    craftSeconds: 10, xpAward: 22,
    colorBreakpoints: { orangeUntil: 59, yellowUntil: 64, greenUntil: 74 },
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  embercured_fillet: {
    id: 'embercured_fillet', name: 'Embercured Fillet', profession: 'cooking', requiredSkill: 100,
    resultItemId: 'embercured_fillet', resultQuantity: 1,
    materials: [{ itemId: 'ember_eel', quantity: 4 }],
    craftSeconds: 12, xpAward: 36,
    colorBreakpoints: { orangeUntil: 109, yellowUntil: 114, greenUntil: 124 },
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  ashfin_chowder: {
    id: 'ashfin_chowder', name: 'Ashfin Chowder', profession: 'cooking', requiredSkill: 150,
    resultItemId: 'ashfin_chowder', resultQuantity: 1,
    materials: [{ itemId: 'ashfin_carp', quantity: 5 }],
    craftSeconds: 14, xpAward: 48,
    colorBreakpoints: { orangeUntil: 159, yellowUntil: 164, greenUntil: 174 },
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  magma_darter_skewers: {
    id: 'magma_darter_skewers', name: 'Magma Darter Skewers', profession: 'cooking', requiredSkill: 200,
    resultItemId: 'magma_darter_skewers', resultQuantity: 1,
    materials: [{ itemId: 'magma_darter', quantity: 5 }],
    craftSeconds: 16, xpAward: 60,
    colorBreakpoints: { orangeUntil: 209, yellowUntil: 214, greenUntil: 224 },
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  emberheart_feast: {
    id: 'emberheart_feast', name: 'Emberheart Feast', profession: 'cooking', requiredSkill: 260,
    resultItemId: 'emberheart_feast', resultQuantity: 1,
    materials: [{ itemId: 'emberheart_koi', quantity: 6 }],
    craftSeconds: 18, xpAward: 75,
    colorBreakpoints: { orangeUntil: 269, yellowUntil: 274, greenUntil: 284 },
    source: 'trainer', rarity: 'rare', learnedAutomatically: true,
  },

  // ── Tailoring bags — permanent inventory capacity (see items.ts).
  small_pack: {
    id: 'small_pack', name: 'Small Pack', profession: 'tailoring', requiredSkill: 10,
    resultItemId: 'small_pack', resultQuantity: 1,
    materials: [{ itemId: 'linen_cloth', quantity: 6 }, { itemId: 'simple_thread', quantity: 2 }],
    craftSeconds: 15, xpAward: 12,
    colorBreakpoints: { orangeUntil: 19, yellowUntil: 24, greenUntil: 34 },
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  travelers_pack: {
    id: 'travelers_pack', name: "Traveler's Pack", profession: 'tailoring', requiredSkill: 60,
    resultItemId: 'travelers_pack', resultQuantity: 1,
    materials: [{ itemId: 'heavy_cloth', quantity: 6 }, { itemId: 'simple_thread', quantity: 3 }],
    craftSeconds: 18, xpAward: 30,
    colorBreakpoints: { orangeUntil: 69, yellowUntil: 74, greenUntil: 84 },
    source: 'trainer', rarity: 'common', learnedAutomatically: true,
  },
  explorers_pack: {
    id: 'explorers_pack', name: "Explorer's Pack", profession: 'tailoring', requiredSkill: 130,
    resultItemId: 'explorers_pack', resultQuantity: 1,
    materials: [{ itemId: 'ashwoven_cloth', quantity: 6 }, { itemId: 'simple_thread', quantity: 3 }],
    craftSeconds: 22, xpAward: 48,
    colorBreakpoints: { orangeUntil: 139, yellowUntil: 144, greenUntil: 154 },
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },
  dwarven_rucksack: {
    id: 'dwarven_rucksack', name: 'Dwarven Rucksack', profession: 'tailoring', requiredSkill: 200,
    resultItemId: 'dwarven_rucksack', resultQuantity: 1,
    materials: [{ itemId: 'charred_cloth', quantity: 6 }, { itemId: 'simple_thread', quantity: 4 }],
    craftSeconds: 26, xpAward: 65,
    colorBreakpoints: { orangeUntil: 209, yellowUntil: 214, greenUntil: 224 },
    source: 'trainer', rarity: 'uncommon', learnedAutomatically: true,
  },

  // ── Blacksmith repairs — converts a damaged dungeon boss drop into its
  // real, equippable form. An ordinary Recipe (materials in, item out),
  // not a bespoke repair system — see items.ts's "_damaged" convention
  // and gameData/types.ts's ItemDef.repairsIntoItemId. requiredSkill
  // scales with the drop's own tier, keeping Blacksmithing relevant deep
  // into Expert/Artisan rather than just the early game.
  repair_overseers_greatmace: {
    id: 'repair_overseers_greatmace', name: "Repair Overseer's Greatmace", profession: 'smithing', requiredSkill: 140,
    resultItemId: 'overseers_greatmace', resultQuantity: 1,
    materials: [{ itemId: 'overseers_greatmace_damaged', quantity: 1 }, { itemId: 'cinderore', quantity: 5 }],
    goldCost: 300,
    craftSeconds: 20, xpAward: 40,
    colorBreakpoints: { orangeUntil: 149, yellowUntil: 154, greenUntil: 164 },
    source: 'dungeon_drop', rarity: 'rare', learnedAutomatically: true,
  },
  repair_pyraxis_warblade: {
    id: 'repair_pyraxis_warblade', name: "Repair Pyraxis's Warblade", profession: 'smithing', requiredSkill: 260,
    resultItemId: 'pyraxis_warblade', resultQuantity: 1,
    materials: [{ itemId: 'pyraxis_warblade_damaged', quantity: 1 }, { itemId: 'emberforge_ore', quantity: 8 }],
    goldCost: 800,
    craftSeconds: 25, xpAward: 80,
    colorBreakpoints: { orangeUntil: 269, yellowUntil: 274, greenUntil: 284 },
    source: 'dungeon_drop', rarity: 'rare', learnedAutomatically: true,
  },

  // ── Taught only by Formula: Emberforged Gauntlets (quests.ts's "The Lost
  // Forge" chain) — not obtainable just by reaching the skill requirement.
  emberforged_gauntlets_recipe: {
    id: 'emberforged_gauntlets_recipe', name: 'Emberforged Gauntlets', profession: 'smithing', requiredSkill: 180,
    resultItemId: 'emberforged_gauntlets', resultQuantity: 1,
    materials: [{ itemId: 'emberforge_ore', quantity: 8 }, { itemId: 'arcane_essence', quantity: 2 }],
    craftSeconds: 22, xpAward: 55,
    colorBreakpoints: { orangeUntil: 189, yellowUntil: 194, greenUntil: 204 },
    source: 'profession_quest', rarity: 'rare', learnedAutomatically: false,
  },
};
