import type { Zone, GatherNode } from './types';

export const DEFAULT_ZONE_ID = 'greenhollow_fields';

export const GATHER_NODES: Record<string, GatherNode> = {
  greenhollow_copper_vein: {
    id: 'greenhollow_copper_vein',
    name: 'Copper Vein',
    profession: 'mining',
    zoneId: 'greenhollow_fields',
    requiredLevel: 1,
    itemId: 'copper_ore',
    xpPerAction: 5,
    secondsPerAction: 8,
  },
  greenhollow_peacebloom_patch: {
    id: 'greenhollow_peacebloom_patch',
    name: 'Peacebloom Patch',
    profession: 'herbalism',
    zoneId: 'greenhollow_fields',
    requiredLevel: 1,
    itemId: 'peacebloom',
    xpPerAction: 5,
    secondsPerAction: 8,
  },
  greenhollow_hunting_grounds: {
    id: 'greenhollow_hunting_grounds',
    name: 'Hunting Grounds',
    profession: 'skinning',
    zoneId: 'greenhollow_fields',
    requiredLevel: 1,
    itemId: 'leather_scraps',
    xpPerAction: 5,
    secondsPerAction: 8,
  },

  stonecrag_tin_vein: {
    id: 'stonecrag_tin_vein',
    name: 'Tin Vein',
    profession: 'mining',
    zoneId: 'stonecrag_foothills',
    requiredLevel: 10,
    itemId: 'tin_ore',
    xpPerAction: 9,
    secondsPerAction: 9,
  },
  stonecrag_sage_patch: {
    id: 'stonecrag_sage_patch',
    name: 'Mountain Sage Patch',
    profession: 'herbalism',
    zoneId: 'stonecrag_foothills',
    requiredLevel: 10,
    itemId: 'mountain_sage',
    xpPerAction: 9,
    secondsPerAction: 9,
  },
  stonecrag_foothill_game: {
    id: 'stonecrag_foothill_game',
    name: 'Foothill Game',
    profession: 'skinning',
    zoneId: 'stonecrag_foothills',
    requiredLevel: 10,
    itemId: 'coarse_hide',
    xpPerAction: 9,
    secondsPerAction: 9,
  },

  emberfall_iron_vein: {
    id: 'emberfall_iron_vein',
    name: 'Iron Vein',
    profession: 'mining',
    zoneId: 'emberfall_ridge',
    requiredLevel: 25,
    itemId: 'iron_ore',
    xpPerAction: 13,
    secondsPerAction: 10,
  },
  emberfall_sunpetal_patch: {
    id: 'emberfall_sunpetal_patch',
    name: 'Sunpetal Patch',
    profession: 'herbalism',
    zoneId: 'emberfall_ridge',
    requiredLevel: 25,
    itemId: 'sunpetal',
    xpPerAction: 13,
    secondsPerAction: 10,
  },
  emberfall_ashfang_den: {
    id: 'emberfall_ashfang_den',
    name: 'Ashfang Den',
    profession: 'skinning',
    zoneId: 'emberfall_ridge',
    requiredLevel: 25,
    itemId: 'scaled_hide',
    xpPerAction: 13,
    secondsPerAction: 10,
  },

  cinderfall_ore_seam: {
    id: 'cinderfall_ore_seam',
    name: 'Cinderore Seam',
    profession: 'mining',
    zoneId: 'cinderfall_depths',
    requiredLevel: 30,
    itemId: 'cinderore',
    xpPerAction: 17,
    secondsPerAction: 11,
  },
  cinderfall_emberpetal_patch: {
    id: 'cinderfall_emberpetal_patch',
    name: 'Emberpetal Patch',
    profession: 'herbalism',
    zoneId: 'cinderfall_depths',
    requiredLevel: 30,
    itemId: 'emberpetal',
    xpPerAction: 17,
    secondsPerAction: 11,
  },
  cinderfall_ash_burrow: {
    id: 'cinderfall_ash_burrow',
    name: 'Ash Burrow',
    profession: 'skinning',
    zoneId: 'cinderfall_depths',
    requiredLevel: 30,
    itemId: 'ashhide',
    xpPerAction: 17,
    secondsPerAction: 11,
  },

  molten_scar_brimstone_vein: {
    id: 'molten_scar_brimstone_vein',
    name: 'Brimstone Vein',
    profession: 'mining',
    zoneId: 'molten_scar',
    requiredLevel: 40,
    itemId: 'brimstone_ore',
    xpPerAction: 21,
    secondsPerAction: 12,
  },
  molten_scar_cinderbloom_patch: {
    id: 'molten_scar_cinderbloom_patch',
    name: 'Cinderbloom Patch',
    profession: 'herbalism',
    zoneId: 'molten_scar',
    requiredLevel: 40,
    itemId: 'cinderbloom',
    xpPerAction: 21,
    secondsPerAction: 12,
  },
  molten_scar_scaleback_den: {
    id: 'molten_scar_scaleback_den',
    name: 'Scaleback Den',
    profession: 'skinning',
    zoneId: 'molten_scar',
    requiredLevel: 40,
    itemId: 'scaleback_hide',
    xpPerAction: 21,
    secondsPerAction: 12,
  },

  cinderheart_ore_vein: {
    id: 'cinderheart_ore_vein',
    name: 'Emberforge Vein',
    profession: 'mining',
    zoneId: 'cinderheart_crater',
    requiredLevel: 48,
    itemId: 'emberforge_ore',
    xpPerAction: 25,
    secondsPerAction: 13,
  },
  cinderheart_bloom_patch: {
    id: 'cinderheart_bloom_patch',
    name: 'Emberheart Patch',
    profession: 'herbalism',
    zoneId: 'cinderheart_crater',
    requiredLevel: 48,
    itemId: 'emberheart_bloom',
    xpPerAction: 25,
    secondsPerAction: 13,
  },
  cinderheart_hide_grounds: {
    id: 'cinderheart_hide_grounds',
    name: 'Emberscale Grounds',
    profession: 'skinning',
    zoneId: 'cinderheart_crater',
    requiredLevel: 48,
    itemId: 'emberscale_hide',
    xpPerAction: 25,
    secondsPerAction: 13,
  },
};

export const ZONES: Record<string, Zone> = {
  greenhollow_fields: {
    id: 'greenhollow_fields',
    name: 'Greenhollow Fields',
    description:
      'A peaceful farming region surrounded by forests and rolling hills. It is the first place new adventurers learn to fight, gather, and explore.',
    levelRange: [1, 15],
    unlockRequirement: { type: 'none' },
    monsterIds: ['greenhorn_boar', 'forest_wolf', 'wild_kobold', 'thornback_hare'],
    gatherNodeIds: ['greenhollow_copper_vein', 'greenhollow_peacebloom_patch', 'greenhollow_hunting_grounds'],
  },

  stonecrag_foothills: {
    id: 'stonecrag_foothills',
    name: 'Stonecrag Foothills',
    description:
      'Windswept slopes and broken rock rising above Greenhollow Fields. Jackals and goats roam the lower trails; bandits and worse hold the higher ground.',
    levelRange: [8, 25],
    unlockRequirement: { type: 'characterLevel', level: 8 },
    monsterIds: ['ridge_jackal', 'craggy_goat', 'rubble_crawler', 'highland_bandit', 'crag_wolf_alpha'],
    gatherNodeIds: ['stonecrag_tin_vein', 'stonecrag_sage_patch', 'stonecrag_foothill_game'],
  },

  emberfall_ridge: {
    id: 'emberfall_ridge',
    name: 'Emberfall Ridge',
    description:
      'A volcanic highland beyond Stonecrag, scarred by old fissures that still breathe heat. Fire-hardened wolves and raiders hold the ridge, and an ancient dwarven forge lies cracked open at its heart.',
    levelRange: [25, 40],
    unlockRequirement: { type: 'characterLevel', level: 25 },
    monsterIds: ['cinder_wolf', 'ashwing_bat', 'molten_crawler', 'ridgeback_marauder', 'scorched_drake'],
    gatherNodeIds: ['emberfall_iron_vein', 'emberfall_sunpetal_patch', 'emberfall_ashfang_den'],
  },

  cinderfall_depths: {
    id: 'cinderfall_depths',
    name: 'Cinderfall Depths',
    description:
      'Once a thriving dwarven mining city, Cinderfall was swallowed by fire and ash generations ago. Its ruins are now home to scavengers, restless spirits, and constructs still obeying orders no living dwarf gave.',
    levelRange: [30, 44],
    unlockRequirement: { type: 'characterLevel', level: 30 },
    monsterIds: ['ash_wraith', 'cinder_scavenger', 'ashforge_golem', 'ember_stalker', 'ruin_marauder'],
    gatherNodeIds: ['cinderfall_ore_seam', 'cinderfall_emberpetal_patch', 'cinderfall_ash_burrow'],
  },

  molten_scar: {
    id: 'molten_scar',
    name: 'The Molten Scar',
    description:
      'A massive rift has torn open the earth here, spilling lava and heat into the world above. Cultists who worship the stirring fire below have made this place their own, and the land itself seems to answer their call.',
    levelRange: [40, 54],
    unlockRequirement: { type: 'characterLevel', level: 40 },
    monsterIds: ['cultist_adept', 'living_ember', 'scaleback_drake', 'cultist_zealot', 'magma_hound'],
    gatherNodeIds: ['molten_scar_brimstone_vein', 'molten_scar_cinderbloom_patch', 'molten_scar_scaleback_den'],
  },

  cinderheart_crater: {
    id: 'cinderheart_crater',
    name: 'Cinderheart Crater',
    description:
      'At the world’s molten heart lies a crater no living thing should call home — yet the fire’s servants gather here in growing numbers, drawn by a power stirring after ages of sleep. This is the frontier of what’s still to come.',
    levelRange: [48, 60],
    unlockRequirement: { type: 'characterLevel', level: 48 },
    monsterIds: ['emberlord_cultist', 'flamewalker', 'charhide_behemoth', 'ashfall_harbinger', 'emberguard_sentinel'],
    gatherNodeIds: ['cinderheart_ore_vein', 'cinderheart_bloom_patch', 'cinderheart_hide_grounds'],
  },
};
