// Dungeon boss abilities (Phase 8) — same Ability/AbilityEffect shape and
// the same generic engine.ts interpreter players use; a boss is just a
// Monster whose equippedAbilityIds points here instead of being empty.
// Every field engine.ts never reads for a monster combatant (class,
// unlockLevel) is set to an arbitrary placeholder, same convention as
// engine.ts's own MONSTER_BASIC_ATTACK. None of these cost a resource —
// monster combatants have no resource pools (see createMonsterCombatant),
// so a resourceType here would make the ability permanently unusable;
// cooldownSeconds alone paces them.
import type { Ability } from './types';

export const MONSTER_ABILITIES: Record<string, Ability> = {
  kobold_chieftain_warcry: {
    id: 'kobold_chieftain_warcry',
    name: 'Chieftain’s Warcry',
    class: 'warrior',
    unlockLevel: 1,
    description: 'Rallies the Chieftain, increasing its own damage dealt for a short time.',
    cooldownSeconds: 30,
    targetType: 'SELF',
    effects: [{ type: 'buff', damageDealtPct: 25, durationSeconds: 8 }],
  },
  kobold_chieftain_bash: {
    id: 'kobold_chieftain_bash',
    name: 'Skullbash',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A heavy overhead blow that stuns.',
    cooldownSeconds: 20,
    targetType: 'CURRENT_ENEMY',
    effects: [
      { type: 'damage', power: 1.1 },
      { type: 'stun', durationSeconds: 3 },
    ],
  },
  kobold_chieftain_slam: {
    id: 'kobold_chieftain_slam',
    name: 'Warlord’s Slam',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A crushing two-handed slam.',
    cooldownSeconds: 10,
    targetType: 'CURRENT_ENEMY',
    effects: [{ type: 'damage', power: 1.4 }],
  },

  alpha_warlord_howl: {
    id: 'alpha_warlord_howl',
    name: 'Warlord’s Howl',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A bone-chilling howl that increases the Warlord’s own damage dealt for a short time.',
    cooldownSeconds: 35,
    targetType: 'SELF',
    effects: [{ type: 'buff', damageDealtPct: 20, durationSeconds: 8 }],
  },
  alpha_warlord_rend: {
    id: 'alpha_warlord_rend',
    name: 'Rend',
    class: 'warrior',
    unlockLevel: 1,
    description: 'Savage claws that leave a bleeding wound.',
    cooldownSeconds: 14,
    targetType: 'CURRENT_ENEMY',
    effects: [{ type: 'dot', power: 0.4, durationSeconds: 12, tickSeconds: 3 }],
  },
  alpha_warlord_pounce: {
    id: 'alpha_warlord_pounce',
    name: 'Pounce',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A sudden, powerful lunge.',
    cooldownSeconds: 9,
    targetType: 'CURRENT_ENEMY',
    effects: [{ type: 'damage', power: 1.5 }],
  },

  kaldrun_warcry: {
    id: 'kaldrun_warcry',
    name: "Forgemaster's Warcry",
    class: 'warrior',
    unlockLevel: 1,
    description: 'Stokes the forge fire within, increasing Kaldrun’s own damage dealt for a short time.',
    cooldownSeconds: 32,
    targetType: 'SELF',
    effects: [{ type: 'buff', damageDealtPct: 30, durationSeconds: 8 }],
  },
  kaldrun_hammerfall: {
    id: 'kaldrun_hammerfall',
    name: 'Hammerfall',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A crushing overhead hammer strike that stuns.',
    cooldownSeconds: 18,
    targetType: 'CURRENT_ENEMY',
    effects: [
      { type: 'damage', power: 1.3 },
      { type: 'stun', durationSeconds: 3 },
    ],
  },
  kaldrun_cinderlash: {
    id: 'kaldrun_cinderlash',
    name: 'Cinderlash',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A wave of molten cinders that leaves a smoldering wound on the whole party.',
    cooldownSeconds: 12,
    targetType: 'CURRENT_ENEMY',
    aoe: true,
    effects: [{ type: 'dot', power: 0.4, durationSeconds: 12, tickSeconds: 3 }],
  },

  ashen_overseer_warcry: {
    id: 'ashen_overseer_warcry',
    name: "Overseer's Command",
    class: 'warrior',
    unlockLevel: 1,
    description: 'An ancient command echoes through the foundry, increasing the Overseer’s own damage dealt for a short time.',
    cooldownSeconds: 32,
    targetType: 'SELF',
    effects: [{ type: 'buff', damageDealtPct: 32, durationSeconds: 8 }],
  },
  ashen_overseer_slam: {
    id: 'ashen_overseer_slam',
    name: 'Foundry Slam',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A crushing mechanical slam that stuns.',
    cooldownSeconds: 18,
    targetType: 'CURRENT_ENEMY',
    effects: [
      { type: 'damage', power: 1.35 },
      { type: 'stun', durationSeconds: 3 },
    ],
  },
  ashen_overseer_cinderwound: {
    id: 'ashen_overseer_cinderwound',
    name: 'Cinderwound',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A gout of buried ash and embers that leaves a smoldering wound.',
    cooldownSeconds: 12,
    targetType: 'CURRENT_ENEMY',
    effects: [{ type: 'dot', power: 0.42, durationSeconds: 12, tickSeconds: 3 }],
  },

  molten_herald_summon: {
    id: 'molten_herald_summon',
    name: 'Rite of the Rift',
    class: 'warrior',
    unlockLevel: 1,
    description: 'Channels the rift’s power, increasing the Herald’s own damage dealt for a short time.',
    cooldownSeconds: 30,
    targetType: 'SELF',
    effects: [{ type: 'buff', damageDealtPct: 34, durationSeconds: 8 }],
  },
  molten_herald_eruption: {
    id: 'molten_herald_eruption',
    name: 'Eruption',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A violent eruption of molten rock that stuns.',
    cooldownSeconds: 17,
    targetType: 'CURRENT_ENEMY',
    effects: [
      { type: 'damage', power: 1.4 },
      { type: 'stun', durationSeconds: 3 },
    ],
  },
  molten_herald_scorch: {
    id: 'molten_herald_scorch',
    name: 'Scorch',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A searing brand that leaves a scorching wound.',
    cooldownSeconds: 11,
    targetType: 'CURRENT_ENEMY',
    effects: [{ type: 'dot', power: 0.45, durationSeconds: 12, tickSeconds: 3 }],
  },

  pyraxis_warcry: {
    id: 'pyraxis_warcry',
    name: "Warden's Roar",
    class: 'warrior',
    unlockLevel: 1,
    description: 'A roar that shakes the crater itself, increasing Pyraxis’s own damage dealt for a short time.',
    cooldownSeconds: 30,
    targetType: 'SELF',
    effects: [{ type: 'buff', damageDealtPct: 36, durationSeconds: 8 }],
  },
  pyraxis_slam: {
    id: 'pyraxis_slam',
    name: 'Cinderheart Slam',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A devastating slam that stuns.',
    cooldownSeconds: 16,
    targetType: 'CURRENT_ENEMY',
    effects: [
      { type: 'damage', power: 1.5 },
      { type: 'stun', durationSeconds: 3 },
    ],
  },
  pyraxis_cinderwound: {
    id: 'pyraxis_cinderwound',
    name: 'Heart of Cinders',
    class: 'warrior',
    unlockLevel: 1,
    description: 'A wound that burns from the inside, fed by the crater’s own heat.',
    cooldownSeconds: 10,
    targetType: 'CURRENT_ENEMY',
    effects: [{ type: 'dot', power: 0.5, durationSeconds: 12, tickSeconds: 3 }],
  },
};
