import type { ClassId } from '../gameData/classStats';
import type { ResourcePool, ResourceType } from './types';

// Which resource pools a class's combatant starts combat with. A class can
// have more than one (Paladin: Mana + Holy Power) — Phase 1 abilities only
// spend Holy Power, but Mana is tracked now so mana-spending Paladin
// abilities in a later phase don't need a resource-model change.
export function initialResources(cls: ClassId, level: number, intStat: number): Partial<Record<ResourceType, ResourcePool>> {
  switch (cls) {
    case 'warrior':
      return { rage: { current: 0, max: 100 } };
    case 'priest': {
      const max = manaMax(level, intStat);
      return { mana: { current: max, max } };
    }
    case 'paladin': {
      const max = manaMax(level, intStat);
      return {
        mana: { current: max, max },
        holyPower: { current: 0, max: 5 },
      };
    }
    case 'mage': {
      const max = manaMax(level, intStat);
      return { mana: { current: max, max } };
    }
  }
}

function manaMax(level: number, intStat: number): number {
  return Math.round(50 + level * 10 + intStat * 2);
}

// Which resource types a class's combatant ever has, in the same order
// initialResources() creates them — used by the Combat Setup screen to only
// offer resource conditions ("if my Mana is below...") that actually apply.
export function resourcesForClass(cls: ClassId): ResourceType[] {
  switch (cls) {
    case 'warrior':
      return ['rage'];
    case 'priest':
      return ['mana'];
    case 'paladin':
      return ['mana', 'holyPower'];
    case 'mage':
      return ['mana'];
  }
}

// Rage decays out of combat and doesn't passively regenerate in combat —
// omitted here on purpose since nothing spends Rage yet in Phase 1. Mana
// regenerates a small percentage of its max every second, in or out of
// combat, matching classic MMO baseline regen. Holy Power has no passive
// regen; it's only generated by abilities.
const MANA_REGEN_PCT_PER_SECOND = 0.02;

export function regenResources(resources: Partial<Record<ResourceType, ResourcePool>>, deltaSeconds: number): void {
  const mana = resources.mana;
  if (mana) {
    mana.current = Math.min(mana.max, mana.current + mana.max * MANA_REGEN_PCT_PER_SECOND * deltaSeconds);
  }
}

export function canAfford(resources: Partial<Record<ResourceType, ResourcePool>>, type: ResourceType | undefined, cost: number | undefined): boolean {
  if (!type || !cost) return true;
  const pool = resources[type];
  return !!pool && pool.current >= cost;
}

export function spend(resources: Partial<Record<ResourceType, ResourcePool>>, type: ResourceType | undefined, cost: number | undefined): void {
  if (!type || !cost) return;
  const pool = resources[type];
  if (pool) pool.current = Math.max(0, pool.current - cost);
}

export function gain(resources: Partial<Record<ResourceType, ResourcePool>>, type: ResourceType | undefined, amount: number | undefined): void {
  if (!type || !amount) return;
  const pool = resources[type];
  if (pool) pool.current = Math.min(pool.max, pool.current + amount);
}
